/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/office_is_old_abandoned_free.glb -o src/components/Environment/AbandonedOffice.tsx -t 
Author: dasy444 (https://sketchfab.com/dasy444)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-is-old-abandoned-free-3977a108b2304b85a698f3dda1777015
Title: office is old abandoned FREE
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import { useGameStore } from '../../store/gameStore'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material004_0: THREE.Mesh
    Cube001_Material005_0: THREE.Mesh
    Cube002_Material004_0: THREE.Mesh
    Cube003_Material005_0: THREE.Mesh
    Plane_Material001_0: THREE.Mesh
    Plane001_Material002_0: THREE.Mesh
    Plane002_Material003_0: THREE.Mesh
    Plane003_Material022_0: THREE.Mesh
    Plane004_Material023_0: THREE.Mesh
    node_0_Material006_0: THREE.Mesh
    node_0001_Material006_0: THREE.Mesh
    node_0002_Material006_0: THREE.Mesh
    node_0003_Material006_0: THREE.Mesh
    node_0004_Material006_0: THREE.Mesh
    node_0005_Material014_0: THREE.Mesh
    node_0006_Material006_0: THREE.Mesh
    node_0007_Material006_0: THREE.Mesh
    node_0008_Material007_0: THREE.Mesh
    node_0009_Material007_0: THREE.Mesh
    node_0010_Material007_0: THREE.Mesh
    node_0011_Material007_0: THREE.Mesh
    node_0012_Material008_0: THREE.Mesh
    node_0013_Material008_0: THREE.Mesh
    node_0014_Material011_0: THREE.Mesh
    node_0015_Material012_0: THREE.Mesh
    node_0016_Material008_0: THREE.Mesh
    node_0017_Material011_0: THREE.Mesh
    node_0018_Material015_0: THREE.Mesh
    node_0019_Material018_0: THREE.Mesh
    node_0020_Material008_0: THREE.Mesh
    node_0021_Material008_0: THREE.Mesh
    node_0022_Material008_0: THREE.Mesh
    node_0023_Material008_0: THREE.Mesh
    node_0024_Material019_0: THREE.Mesh
    node_0025_Material006_0: THREE.Mesh
    node_0026_Material012_0: THREE.Mesh
    node_0027_Material014_0: THREE.Mesh
    node_0028_Material011_0: THREE.Mesh
    node_0029_Material006_0: THREE.Mesh
    node_0030_Material014_0: THREE.Mesh
    node_0031_Material020_0: THREE.Mesh
    node_0032_Material021_0: THREE.Mesh
    node_0033_Material021_0: THREE.Mesh
    node_0034_Material007_0: THREE.Mesh
    node_0035_Material014_0: THREE.Mesh
    node_0036_Material018_0: THREE.Mesh
    node_0037_Material014_0: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function AbandonedOffice(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/office_is_old_abandoned_free.glb') as GLTFResult
  const { setActivePuzzle } = useGameStore()

  return (
    <>
      <RigidBody type="fixed">
        {/* Invisible boundaries to keep player in the room */}
        <CuboidCollider args={[50, 0.5, 50]} position={[0, -0.5, 0]} />
        <CuboidCollider args={[50, 0.5, 50]} position={[0, 4.5, 0]} />
        <CuboidCollider args={[0.5, 5, 50]} position={[-5.0, 2.5, 0]} />
        <CuboidCollider args={[0.5, 5, 50]} position={[4.0, 2.5, 0]} />
        <CuboidCollider args={[50, 5, 0.5]} position={[0, 2.5, -5.0]} />
        <CuboidCollider args={[50, 5, 0.5]} position={[0, 2.5, 5.0]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="trimesh">
        <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} position={[-340.773, 87.697, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'The Nexus Terminal', interactable: true, onInteract: () => setActivePuzzle(12) }} />
        <mesh geometry={nodes.Cube001_Material005_0.geometry} material={materials['Material.005']} position={[-341.534, 45.621, 319.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'The Quantum Mainframe', interactable: true, onInteract: () => setActivePuzzle(13) }} />
        <mesh geometry={nodes.Cube002_Material004_0.geometry} material={materials['Material.004']} position={[261.226, 87.697, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'The Genesis Core', interactable: true, onInteract: () => setActivePuzzle(14) }} />
        <mesh geometry={nodes.Cube003_Material005_0.geometry} material={materials['Material.005']} position={[260.464, 45.621, 319.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane001_Material002_0.geometry} material={materials['Material.002']} position={[-390.825, 127.985, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane002_Material003_0.geometry} material={materials['Material.003']} position={[-390.825, 174.577, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane003_Material022_0.geometry} material={materials['Material.022']} position={[-51.005, 206.576, -405.465]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane004_Material023_0.geometry} material={materials['Material.023']} position={[0, 323.532, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0_Material006_0.geometry} material={materials['Material.006']} position={[-362.778, 89.538, 169.681]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0001_Material006_0.geometry} material={materials['Material.006']} position={[-358.79, 109.5, 52.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0002_Material006_0.geometry} material={materials['Material.006']} position={[-371.343, 89.538, -301.845]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0003_Material006_0.geometry} material={materials['Material.006']} position={[-366.543, 89.538, -223.253]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0004_Material006_0.geometry} material={materials['Material.006']} position={[-373.558, 89.538, -172.455]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0005_Material014_0.geometry} material={materials['Material.014']} position={[-325.609, 87.868, -132.171]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0006_Material006_0.geometry} material={materials['Material.006']} position={[-358.79, 89.538, 338.492]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0007_Material006_0.geometry} material={materials['Material.006']} position={[-358.79, 89.538, 388.552]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0008_Material007_0.geometry} material={materials['Material.007']} position={[-320.191, 89.049, -198.102]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0009_Material007_0.geometry} material={materials['Material.007']} position={[-326.844, 89.049, -260.368]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0010_Material007_0.geometry} material={materials['Material.007']} position={[-376.714, 89.049, 118.541]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0011_Material007_0.geometry} material={materials['Material.007']} position={[-316.568, 89.049, 330.948]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0012_Material008_0.geometry} material={materials['Material.008']} position={[-249.087, 0, 146.76]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0013_Material008_0.geometry} material={materials['Material.008']} position={[-245.67, 33.966, -198.46]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0014_Material011_0.geometry} material={materials['Material.011']} position={[-345.644, 0, -134.178]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0015_Material012_0.geometry} material={materials['Material.012']} position={[-349.058, 91.083, -47.404]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0016_Material008_0.geometry} material={materials['Material.008']} position={[-249.087, 0, -324.541]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0017_Material011_0.geometry} material={materials['Material.011']} position={[-332.303, 88.039, 252.86]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0018_Material015_0.geometry} material={materials['Material.015']} position={[-275.521, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0019_Material018_0.geometry} material={materials['Material.018']} position={[-344.737, 0, 35.719]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0020_Material008_0.geometry} material={materials['Material.008']} position={[155.127, 0, 87.965]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0021_Material008_0.geometry} material={materials['Material.008']} position={[139.51, 0, -307.063]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0022_Material008_0.geometry} material={materials['Material.008']} position={[145.94, 0, -2.983]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0023_Material008_0.geometry} material={materials['Material.008']} position={[149.404, 33.966, 240.349]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0024_Material019_0.geometry} material={materials['Material.019']} position={[-321.607, 0, 290.29]} rotation={[-Math.PI / 2, 0, 0]} scale={118.417} />
        <mesh geometry={nodes.node_0025_Material006_0.geometry} material={materials['Material.006']} position={[273.078, 109.5, -139.58]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0026_Material012_0.geometry} material={materials['Material.012']} position={[252.628, 91.083, 268.278]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0027_Material014_0.geometry} material={materials['Material.014']} position={[269.753, 87.868, 369.122]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0028_Material011_0.geometry} material={materials['Material.011']} position={[270.935, 89.218, -347.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0029_Material006_0.geometry} material={materials['Material.006']} position={[247.815, 109.5, -371.544]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0030_Material014_0.geometry} material={materials['Material.014']} position={[276.885, 87.868, -260.019]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0031_Material020_0.geometry} material={materials['Material.020']} position={[-141.675, 0, -343.213]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0032_Material021_0.geometry} material={materials['Material.021']} position={[253.159, 89.322, -51.889]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0033_Material021_0.geometry} material={materials['Material.021']} position={[253.159, -0.883, 241.664]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0034_Material007_0.geometry} material={materials['Material.007']} position={[283.425, 89.049, 157.604]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0035_Material014_0.geometry} material={materials['Material.014']} position={[271.17, 87.868, 54.903]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0036_Material018_0.geometry} material={materials['Material.018']} position={[211.769, 0, -194.198]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.node_0037_Material014_0.geometry} material={materials['Material.014']} position={[271.17, 1.068, 30.751]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
        </group>
      </RigidBody>
    </>
  )
}

useGLTF.preload('/office_is_old_abandoned_free.glb')
