/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/day_3._abandoned_school_room.glb -o src/components/Environment/AbandonedSchoolRoom.tsx -t 
Author: Olyona Kuznetsova (https://sketchfab.com/olyona.kuznetsova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/day-3-abandoned-school-room-36232d02c99f480f8427fb77a92c48ce
Title: Day 3. Abandoned school room
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import { useGameStore } from '../../store/gameStore'

type GLTFResult = GLTF & {
  nodes: {
    Plane_wall_0: THREE.Mesh
    Plane_Brick_0: THREE.Mesh
    Plane001_Black_0: THREE.Mesh
    Plane001_dask_0: THREE.Mesh
    Plane010_wall_0: THREE.Mesh
    Plane012_Floor_0: THREE.Mesh
    Plane015_wall_0: THREE.Mesh
    Plane015_Brick_0: THREE.Mesh
    Plane016_Brick_0: THREE.Mesh
    Plane018_Brick_0: THREE.Mesh
    Plane019_wall_0: THREE.Mesh
    Plane039_white_0: THREE.Mesh
    Plane048_wall_0: THREE.Mesh
    Plane002_table_0: THREE.Mesh
    Plane002_metalic_0: THREE.Mesh
    Plane043_table_0: THREE.Mesh
    Plane043_metalic_0: THREE.Mesh
    Plane044_table_0: THREE.Mesh
    Plane044_metalic_0: THREE.Mesh
    Plane028_table_0: THREE.Mesh
    Plane028_metalic_0: THREE.Mesh
    Plane046_table_0: THREE.Mesh
    Plane046_metalic_0: THREE.Mesh
    Plane004_woosstul_0: THREE.Mesh
    Plane004_metalic_0: THREE.Mesh
    Plane003_woosstul_0: THREE.Mesh
    Plane003_metalic_0: THREE.Mesh
    Plane005_woosstul_0: THREE.Mesh
    Plane005_metalic_0: THREE.Mesh
    Plane006_woosstul_0: THREE.Mesh
    Plane006_metalic_0: THREE.Mesh
    Plane007_woosstul_0: THREE.Mesh
    Plane007_metalic_0: THREE.Mesh
    Plane008_woosstul_0: THREE.Mesh
    Plane008_metalic_0: THREE.Mesh
    Plane041_woosstul_0: THREE.Mesh
    Plane041_metalic_0: THREE.Mesh
    Plane042_woosstul_0: THREE.Mesh
    Plane042_metalic_0: THREE.Mesh
    Plane029_woosstul_0: THREE.Mesh
    Plane029_metalic_0: THREE.Mesh
    Plane045_woosstul_0: THREE.Mesh
    Plane045_metalic_0: THREE.Mesh
    Plane047_woosstul_0: THREE.Mesh
    Plane047_metalic_0: THREE.Mesh
    Circle_clock_0: THREE.Mesh
    Circle001_Glossclock_0: THREE.Mesh
    Plane009_Strel_0: THREE.Mesh
    Cube002_wood2_0: THREE.Mesh
    Cube003_wood1_0: THREE.Mesh
    Cube006_wood1_0: THREE.Mesh
    Cube007_wood_0: THREE.Mesh
    Cube010_table2_0: THREE.Mesh
    Plane013_bleu_0: THREE.Mesh
    Plane013_yellowdark_0: THREE.Mesh
    Plane014_yellow_0: THREE.Mesh
    Plane014_bleu_0: THREE.Mesh
    Cube_rama_0: THREE.Mesh
    Cube001_rama_0: THREE.Mesh
    Sphere_Blueglobus_0: THREE.Mesh
    Sphere_Black_0: THREE.Mesh
    Plane040_wood_0: THREE.Mesh
    Plane040_map_0: THREE.Mesh
    Plane050_global_0: THREE.Mesh
    Plane051_virus_0: THREE.Mesh
    Plane052_virus_0: THREE.Mesh
    Cube008_bluemagnit_0: THREE.Mesh
    Cube009_bluemagnit_0: THREE.Mesh
    Cube011_bluemagnit_0: THREE.Mesh
    Cube012_bluemagnit_0: THREE.Mesh
    Plane054_paper_0: THREE.Mesh
    Plane054_book_0: THREE.Mesh
    Plane054_book2_0: THREE.Mesh
    Sphere002_Blueglobus_0: THREE.Mesh
    Sphere002_Black_0: THREE.Mesh
    Sphere001_Blueglobus_0: THREE.Mesh
    Sphere001_Black_0: THREE.Mesh
    Plane053_metalic_0: THREE.Mesh
    Plane053_red_0: THREE.Mesh
    Plane053_wood1_0: THREE.Mesh
    Cylinder_Pensil1_0: THREE.Mesh
    Cylinder_paper_0: THREE.Mesh
    Cylinder_Pensil2_0: THREE.Mesh
    Cylinder_metalic_0: THREE.Mesh
    Cylinder001_Pensil1_0: THREE.Mesh
    Cylinder001_paper_0: THREE.Mesh
    Cylinder001_Pensil2_0: THREE.Mesh
    Cylinder001_metalic_0: THREE.Mesh
    Cylinder001_book3_0: THREE.Mesh
    Cylinder001_badb_0: THREE.Mesh
    Cylinder001_kros_0: THREE.Mesh
    Cylinder002_Pensil1_0: THREE.Mesh
    Cylinder002_paper_0: THREE.Mesh
    Cylinder002_Pensil2_0: THREE.Mesh
    Cylinder002_metalic_0: THREE.Mesh
    Plane063_poster_0: THREE.Mesh
    Plane064_poster2_0: THREE.Mesh
    Cube004_book1_0: THREE.Mesh
    Cube004_paper_0: THREE.Mesh
    Cube004_book2_0: THREE.Mesh
    Cube004_book3_0: THREE.Mesh
    Plane022_glass_0: THREE.Mesh
    Plane023_glass_0: THREE.Mesh
    Plane021_glass_0: THREE.Mesh
    Plane024_glass_0: THREE.Mesh
    Plane025_glass_0: THREE.Mesh
    Plane026_glass_0: THREE.Mesh
    Plane027_glass_0: THREE.Mesh
    Plane030_wood1_0: THREE.Mesh
    Plane032_wood1_0: THREE.Mesh
    Plane033_wood2_0: THREE.Mesh
    Plane034_wood1_0: THREE.Mesh
    Plane035_wood1_0: THREE.Mesh
    Plane036_wood2_0: THREE.Mesh
    Plane037_wood2_0: THREE.Mesh
    Circle002_Black_0: THREE.Mesh
    Circle002_bluemagnit_0: THREE.Mesh
    Circle003_setka_0: THREE.Mesh
    Circle004_Black_0: THREE.Mesh
    Circle004_bluemagnit_0: THREE.Mesh
    Circle005_setka_0: THREE.Mesh
    Cube013_wHITE_0: THREE.Mesh
    Cube013_bluemagnit_0: THREE.Mesh
    Plane049_paperwhite_0: THREE.Mesh
    Plane017_Material002_0: THREE.Mesh
    Plane055_Material002_0: THREE.Mesh
    Plane056_paperwhite_0: THREE.Mesh
    Plane057_paperwhite_0: THREE.Mesh
    Plane058_paperwhite_0: THREE.Mesh
    Plane059_paperwhite_0: THREE.Mesh
    Plane060_paperwhite_0: THREE.Mesh
    Plane061_paperwhite_0: THREE.Mesh
    Plane011_poster3_0: THREE.Mesh
    Plane065_poster3_0: THREE.Mesh
    Plane066_Material_0: THREE.Mesh
    Plane068_Material_0: THREE.Mesh
    Plane069_Material_0: THREE.Mesh
    Plane070_Material_0: THREE.Mesh
    Plane071_Material_0: THREE.Mesh
    Plane067_Material_0: THREE.Mesh
    Plane072_paperwhite_0: THREE.Mesh
    Plane073_paperwhite_0: THREE.Mesh
    Plane074_paperwhite_0: THREE.Mesh
    Plane076_paperwhite_0: THREE.Mesh
    Plane077_paperwhite_0: THREE.Mesh
    Plane078_Black_0: THREE.Mesh
    Plane079_Material001_0: THREE.Mesh
    Vert001_black2_0: THREE.Mesh
    Vert004_black2_0: THREE.Mesh
    Vert003_black2_0: THREE.Mesh
    Vert005_black2_0: THREE.Mesh
    Plane081_metalic_0: THREE.Mesh
    Plane081_lamp_0: THREE.Mesh
    Plane080_metalic_0: THREE.Mesh
    Plane080_lamp_0: THREE.Mesh
    Plane082_metalic_0: THREE.Mesh
    Plane082_lamp_0: THREE.Mesh
    Plane083_metalic_0: THREE.Mesh
    Plane083_lamp_0: THREE.Mesh
    Plane089_lamp2_0: THREE.Mesh
    Plane075_paperwhite_0: THREE.Mesh
  }
  materials: {
    wall: THREE.MeshStandardMaterial
    Brick: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    dask: THREE.MeshStandardMaterial
    Floor: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    table: THREE.MeshStandardMaterial
    metalic: THREE.MeshStandardMaterial
    ['woos.stul']: THREE.MeshStandardMaterial
    clock: THREE.MeshStandardMaterial
    ['Gloss.clock']: THREE.MeshStandardMaterial
    Strel: THREE.MeshStandardMaterial
    wood2: THREE.MeshStandardMaterial
    wood1: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['table.2']: THREE.MeshStandardMaterial
    bleu: THREE.MeshStandardMaterial
    ['yellow.dark']: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    rama: THREE.MeshStandardMaterial
    ['Blue.globus']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    global: THREE.MeshStandardMaterial
    virus: THREE.MeshStandardMaterial
    ['blue.magnit']: THREE.MeshStandardMaterial
    paper: THREE.MeshStandardMaterial
    book: THREE.MeshStandardMaterial
    book2: THREE.MeshStandardMaterial
    material_28: THREE.MeshStandardMaterial
    Pensil1: THREE.MeshStandardMaterial
    ['Pensil.2']: THREE.MeshStandardMaterial
    book3: THREE.MeshStandardMaterial
    badb: THREE.MeshStandardMaterial
    kros: THREE.MeshStandardMaterial
    poster: THREE.MeshStandardMaterial
    poster2: THREE.MeshStandardMaterial
    book1: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    setka: THREE.MeshStandardMaterial
    wHITE: THREE.MeshStandardMaterial
    ['paper.white']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    poster3: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['black.2']: THREE.MeshStandardMaterial
    lamp: THREE.MeshStandardMaterial
    lamp2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function AbandonedSchoolRoom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/day_3._abandoned_school_room.glb') as GLTFResult
  const { setActivePuzzle, setBookModalOpen } = useGameStore()
  
  return (
    <>
      <RigidBody type="fixed">
        {/* Invisible boundaries to keep player in the room */}
        <CuboidCollider args={[50, 0.5, 50]} position={[0, -0.5, 0]} />
        <CuboidCollider args={[50, 0.5, 50]} position={[0, 4.5, 0]} />
        <CuboidCollider args={[0.5, 5, 50]} position={[-5.2, 2.5, 0]} />
        <CuboidCollider args={[0.5, 5, 50]} position={[6.6, 2.5, 0]} />
        <CuboidCollider args={[50, 5, 0.5]} position={[0, 2.5, -5.2]} />
        <CuboidCollider args={[50, 5, 0.5]} position={[0, 2.5, 6.6]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="trimesh">
        <group {...props} dispose={null}>
      <group scale={0.005} position={[0, 0, 0]}>
        <group position={[4.36, 0.646, -276.474]} scale={[11.642, 0.778, 7.715]}>
          <mesh geometry={nodes.Plane_wall_0.geometry} material={materials.wall} />
          <mesh geometry={nodes.Plane_Brick_0.geometry} material={materials.Brick} />
        </group>
        <group position={[4.7, -10.322, -268.428]} rotation={[-0.037, -0.003, -0.002]} scale={[9.307, 0.622, 6.167]}>
        <mesh geometry={nodes.Plane001_Black_0.geometry} material={materials.Black} />
        <mesh 
          geometry={nodes.Plane001_dask_0.geometry} 
          material={materials.dask} 
          userData={{ name: 'The Blackboard', interactable: true, onInteract: () => setActivePuzzle(9) }} 
        />
      </group>
        <group position={[4.36, 0.646, -276.474]} scale={[11.642, 0.778, 7.715]}>
          <mesh geometry={nodes.Plane015_wall_0.geometry} material={materials.wall} />
          <mesh geometry={nodes.Plane015_Brick_0.geometry} material={materials.Brick} />
        </group>
        <group position={[281.296, 245.072, -329.455]} scale={[0.906, 0.958, 2.141]}>
          <mesh geometry={nodes.Plane002_table_0.geometry} material={materials.table} />
          <mesh geometry={nodes.Plane002_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-643.465, 104.949, 1006.624]} rotation={[-0.001, -0.809, -1.574]} scale={[0.906, 0.906, 1.954]}>
          <mesh geometry={nodes.Plane043_table_0.geometry} material={materials.table} />
          <mesh geometry={nodes.Plane043_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-477.851, 122.201, -875.361]} rotation={[0, Math.PI / 2, 0]} scale={[1.01, 0.957, 2.342]}>
          <mesh geometry={nodes.Plane044_table_0.geometry} material={materials.table} />
          <mesh geometry={nodes.Plane044_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-513.145, 370.855, -875.361]} rotation={[-Math.PI, -1.381, 0]} scale={[1.01, 0.957, 2.342]}>
          <mesh geometry={nodes.Plane028_table_0.geometry} material={materials.table} />
          <mesh geometry={nodes.Plane028_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-176.556, 129.882, 1070.05]} rotation={[-Math.PI, -1.204, -Math.PI]} scale={[0.906, 0.906, 1.954]}>
          <mesh geometry={nodes.Plane046_table_0.geometry} material={materials.table} />
          <mesh geometry={nodes.Plane046_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-175.299, 143.804, 904.519]} rotation={[0, -1.188, 0]} scale={[0.586, 0.918, 0.597]}>
          <mesh geometry={nodes.Plane004_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane004_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-176.736, 391.19, 1066.199]} rotation={[0, 0.354, 0]} scale={[0.586, 0.918, 0.597]}>
          <mesh geometry={nodes.Plane003_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane003_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[442.61, 129.76, -853.393]} rotation={[-Math.PI, -1.525, -Math.PI]} scale={[0.529, 0.829, 0.539]}>
          <mesh geometry={nodes.Plane005_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane005_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[581.197, 129.76, -853.393]} rotation={[-Math.PI, -1.452, -Math.PI]} scale={[0.529, 0.829, 0.539]}>
          <mesh geometry={nodes.Plane006_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane006_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[720.62, 129.76, -853.393]} rotation={[0, -1.517, 0]} scale={[0.529, 0.829, 0.539]}>
          <mesh geometry={nodes.Plane007_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane007_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[442.61, 259.572, -836.413]} rotation={[2.915, -1.446, 2.965]} scale={[0.529, 0.829, 0.539]}>
          <mesh geometry={nodes.Plane008_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane008_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[580.439, 259.572, -836.413]} rotation={[0, -1.497, 0]} scale={[0.529, 0.829, 0.539]}>
          <mesh geometry={nodes.Plane041_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane041_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[717.433, 259.572, -836.413]} rotation={[-Math.PI, -1.333, -Math.PI]} scale={[0.529, 0.829, 0.539]}>
          <mesh geometry={nodes.Plane042_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane042_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[189.141, 272.235, -204.939]} rotation={[1.532, -0.006, 0.006]} scale={[0.586, 0.918, 0.597]}>
          <mesh geometry={nodes.Plane029_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane029_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[-874.942, 143.995, -898.977]} rotation={[0, -0.918, 0]} scale={[0.586, 0.918, 0.597]}>
          <mesh geometry={nodes.Plane045_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane045_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[217.588, 143.995, -338.654]} scale={[0.586, 0.918, 0.597]}>
          <mesh geometry={nodes.Plane047_woosstul_0.geometry} material={materials['woos.stul']} />
          <mesh geometry={nodes.Plane047_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[990.862, 10.635, 905.816]}>
          <mesh geometry={nodes.Plane013_bleu_0.geometry} material={materials.bleu} />
          <mesh geometry={nodes.Plane013_yellowdark_0.geometry} material={materials['yellow.dark']} />
        </group>
        <group position={[990.862, 10.635, 905.816]}>
          <mesh geometry={nodes.Plane014_yellow_0.geometry} material={materials.yellow} />
          <mesh geometry={nodes.Plane014_bleu_0.geometry} material={materials.bleu} />
        </group>
        <group position={[1121.001, 369.25, -645.451]}>
        <mesh 
          geometry={nodes.Sphere_Blueglobus_0.geometry} 
          material={materials['Blue.globus']} 
          userData={{ name: 'The Globe', interactable: true, onInteract: () => setActivePuzzle(11) }} 
        />
        <mesh geometry={nodes.Sphere_Black_0.geometry} material={materials.Black} />
      </group>
        <group position={[766.827, 2.283, 108.323]} rotation={[0, 0, Math.PI]} scale={[2.13, 1, 1.255]}>
          <mesh geometry={nodes.Plane040_wood_0.geometry} material={materials.wood} />
          <mesh geometry={nodes.Plane040_map_0.geometry} material={materials.material} />
        </group>
        <group position={[1031.109, 14.331, 392.342]} rotation={[0, 0.497, 0]} scale={[0.413, 0.413, 0.304]}>
          <mesh geometry={nodes.Plane054_paper_0.geometry} material={materials.paper} />
          <mesh geometry={nodes.Plane054_book_0.geometry} material={materials.book} />
          <mesh geometry={nodes.Plane054_book2_0.geometry} material={materials.book2} />
        </group>
        <group position={[1059.038, 17.766, -875.556]} rotation={[0, 0.679, 0]} scale={0.358}>
          <mesh geometry={nodes.Sphere002_Blueglobus_0.geometry} material={materials['Blue.globus']} />
          <mesh geometry={nodes.Sphere002_Black_0.geometry} material={materials.Black} />
        </group>
        <group position={[1062.455, 9.827, -765.039]} rotation={[0, 0.679, 0]} scale={0.399}>
          <mesh geometry={nodes.Sphere001_Blueglobus_0.geometry} material={materials['Blue.globus']} />
          <mesh geometry={nodes.Sphere001_Black_0.geometry} material={materials.Black} />
        </group>
        <group position={[-442.797, 304.432, -835.332]} rotation={[0.183, 0.799, -1.813]} scale={0.21}>
          <mesh geometry={nodes.Plane053_metalic_0.geometry} material={materials.metalic} />
          <mesh geometry={nodes.Plane053_red_0.geometry} material={materials.material_28} />
          <mesh geometry={nodes.Plane053_wood1_0.geometry} material={materials.wood1} />
        </group>
        <group position={[251.687, 248.101, -183.815]} scale={0.051}>
          <mesh geometry={nodes.Cylinder_Pensil1_0.geometry} material={materials.Pensil1} />
          <mesh geometry={nodes.Cylinder_paper_0.geometry} material={materials.paper} />
          <mesh geometry={nodes.Cylinder_Pensil2_0.geometry} material={materials['Pensil.2']} />
          <mesh geometry={nodes.Cylinder_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[299.827, 255.288, -500.72]} rotation={[-0.032, -0.788, 0.047]} scale={[0.034, 0.051, 0.051]}>
          <mesh geometry={nodes.Cylinder001_Pensil1_0.geometry} material={materials.Pensil1} />
          <mesh geometry={nodes.Cylinder001_paper_0.geometry} material={materials.paper} />
          <mesh geometry={nodes.Cylinder001_Pensil2_0.geometry} material={materials['Pensil.2']} />
          <mesh geometry={nodes.Cylinder001_metalic_0.geometry} material={materials.metalic} />
          <mesh geometry={nodes.Cylinder001_book3_0.geometry} material={materials.book3} />
          <mesh geometry={nodes.Cylinder001_badb_0.geometry} material={materials.badb} />
          <mesh geometry={nodes.Cylinder001_kros_0.geometry} material={materials.kros} />
        </group>
        <group position={[251.687, 249.321, -177.156]} rotation={[-3.069, 1.259, -Math.PI]} scale={[0.034, 0.051, 0.051]}>
          <mesh geometry={nodes.Cylinder002_Pensil1_0.geometry} material={materials.Pensil1} />
          <mesh geometry={nodes.Cylinder002_paper_0.geometry} material={materials.paper} />
          <mesh geometry={nodes.Cylinder002_Pensil2_0.geometry} material={materials['Pensil.2']} />
          <mesh geometry={nodes.Cylinder002_metalic_0.geometry} material={materials.metalic} />
        </group>
        <group position={[1115.734, 188.204, -745.103]}>
          <mesh
            geometry={nodes.Cube004_book1_0.geometry}
            material={materials.book1}
            userData={{ name: 'Study Notes', interactable: true, onInteract: () => setBookModalOpen(true) }}
          />
          <mesh geometry={nodes.Cube004_paper_0.geometry} material={materials.paper} />
          <mesh geometry={nodes.Cube004_book2_0.geometry} material={materials.book2} />
          <mesh geometry={nodes.Cube004_book3_0.geometry} material={materials.book3} />
        </group>
        <group position={[258.434, 245.822, -386.998]} rotation={[0, -1.298, 0]} scale={[0.39, 0.5, 0.397]}>
          <mesh geometry={nodes.Circle002_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Circle002_bluemagnit_0.geometry} material={materials['blue.magnit']} />
        </group>
        <group position={[328.971, 245.822, -410.181]} rotation={[-0.071, -0.427, -0.047]} scale={[0.39, 0.5, 0.397]}>
          <mesh geometry={nodes.Circle004_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Circle004_bluemagnit_0.geometry} material={materials['blue.magnit']} />
        </group>
        <group position={[253.006, 263.17, -517.013]} scale={[0.613, 0.676, 0.613]}>
          <mesh geometry={nodes.Cube013_wHITE_0.geometry} material={materials.wHITE} />
          <mesh geometry={nodes.Cube013_bluemagnit_0.geometry} material={materials['blue.magnit']} />
        </group>
        <group position={[579.286, 994.056, 580.127]} scale={[0.37, 1.639, 1.964]}>
          <mesh geometry={nodes.Plane081_metalic_0.geometry} material={materials.metalic} />
          <mesh geometry={nodes.Plane081_lamp_0.geometry} material={materials.lamp} />
        </group>
        <group position={[579.286, 1007.394, -370.138]} scale={[0.37, 1.639, 1.964]}>
          <mesh geometry={nodes.Plane080_metalic_0.geometry} material={materials.metalic} />
          <mesh geometry={nodes.Plane080_lamp_0.geometry} material={materials.lamp} />
        </group>
        <group position={[-285.991, 1007.394, -370.138]} scale={[0.37, 1.639, 1.964]}>
          <mesh geometry={nodes.Plane082_metalic_0.geometry} material={materials.metalic} />
          <mesh geometry={nodes.Plane082_lamp_0.geometry} material={materials.lamp} />
        </group>
        <group position={[-255.716, 36.961, 580.127]} scale={[0.37, 1.639, 1.964]}>
          <mesh geometry={nodes.Plane083_metalic_0.geometry} material={materials.metalic} />
          <mesh geometry={nodes.Plane083_lamp_0.geometry} material={materials.lamp} />
        </group>
        <mesh geometry={nodes.Plane010_wall_0.geometry} material={materials.wall} position={[4.36, 0.646, -276.474]} scale={[11.642, 0.778, 7.715]} />
        <mesh geometry={nodes.Plane012_Floor_0.geometry} material={materials.Floor} position={[4.36, 0.646, -276.474]} scale={[11.642, 0.778, 7.715]} />
        <mesh geometry={nodes.Plane016_Brick_0.geometry} material={materials.Brick} position={[-48.647, 530.411, -979.408]} scale={[11.642, 0.778, 7.715]} />
        <mesh geometry={nodes.Plane018_Brick_0.geometry} material={materials.Brick} position={[4.36, 0.646, -276.474]} scale={[11.642, 0.778, 7.715]} />
        <mesh geometry={nodes.Plane019_wall_0.geometry} material={materials.wall} position={[-509.9, 913.597, -649.241]} scale={[11.642, 0.778, 7.715]} />
        <mesh geometry={nodes.Plane039_white_0.geometry} material={materials.white} position={[4.7, -10.322, -268.428]} rotation={[-0.037, -0.003, -0.002]} scale={[9.307, 0.622, 6.167]} />
        <mesh geometry={nodes.Plane048_wall_0.geometry} material={materials.wall} position={[-509.9, 913.597, -649.241]} scale={[11.642, 0.778, 7.715]} />
      <mesh 
        geometry={nodes.Circle_clock_0.geometry} 
        material={materials.clock} 
        position={[1158.492, 824.815, 50.564]} 
        rotation={[0, -0.09, 0]} 
        scale={0.799} 
        userData={{ name: 'The Broken Clock', interactable: true, onInteract: () => setActivePuzzle(10) }} 
      />
      <mesh geometry={nodes.Circle001_Glossclock_0.geometry} material={materials['Gloss.clock']} position={[1153.121, 831.654, 38.341]} rotation={[0, -0.09, 0]} scale={0.799} />
        <mesh geometry={nodes.Plane009_Strel_0.geometry} material={materials.Strel} position={[1165.052, 833.654, 64.017]} rotation={[0, -0.09, -Math.PI / 2]} scale={[0.169, 0.169, 0.026]} />
        <mesh geometry={nodes.Cube002_wood2_0.geometry} material={materials.wood2} position={[1073.47, 617.486, -753.196]} scale={0.799} />
        <mesh geometry={nodes.Cube003_wood1_0.geometry} material={materials.wood1} position={[1073.47, 618.389, -753.196]} scale={0.799} />
        <mesh geometry={nodes.Cube006_wood1_0.geometry} material={materials.wood1} position={[1073.47, 617.486, -753.196]} scale={0.799} />
        <mesh geometry={nodes.Cube007_wood_0.geometry} material={materials.wood} position={[1073.47, 617.486, -753.196]} scale={0.799} />
        <mesh geometry={nodes.Cube010_table2_0.geometry} material={materials['table.2']} position={[574.621, 96.334, 664.43]} rotation={[0, -0.198, 0]} scale={[0.568, 1, 1]} />
        <mesh geometry={nodes.Cube_rama_0.geometry} material={materials.rama} position={[-598.572, 592.834, -1067.287]} />
        <mesh geometry={nodes.Cube001_rama_0.geometry} material={materials.rama} position={[607.995, 592.834, -1067.287]} scale={[1, 0.967, 1]} />
        <mesh geometry={nodes.Plane050_global_0.geometry} material={materials.global} position={[287.377, 245.917, -178.773]} scale={[0.519, 0.519, 0.417]} />
        <mesh geometry={nodes.Plane051_virus_0.geometry} material={materials.virus} position={[243.36, 246.658, -154.853]} rotation={[0, 1.225, 0]} />
        <mesh geometry={nodes.Plane052_virus_0.geometry} material={materials.virus} position={[237.637, 247.345, -167.018]} rotation={[0, -1.45, 0]} />
        <mesh geometry={nodes.Cube008_bluemagnit_0.geometry} material={materials['blue.magnit']} position={[793.215, 5.973, 77.426]} scale={0.588} />
        <mesh geometry={nodes.Cube009_bluemagnit_0.geometry} material={materials['blue.magnit']} position={[1163.381, 444.941, 281.639]} rotation={[-0.037, -0.003, -1.573]} scale={1.405} />
        <mesh geometry={nodes.Cube011_bluemagnit_0.geometry} material={materials['blue.magnit']} position={[1163.134, 474.507, 390.311]} rotation={[-0.037, -0.003, -1.573]} scale={1.405} />
        <mesh geometry={nodes.Cube012_bluemagnit_0.geometry} material={materials['blue.magnit']} position={[1163.338, 523.218, 358.065]} rotation={[-0.037, -0.003, -1.573]} scale={1.405} />
        <mesh geometry={nodes.Plane063_poster_0.geometry} material={materials.poster} position={[-538.682, 627.23, 1273.688]} rotation={[Math.PI / 2, 0, 0]} scale={1.838} />
        <mesh geometry={nodes.Plane064_poster2_0.geometry} material={materials.poster2} position={[-1837.883, 991.048, 650.353]} rotation={[Math.PI / 2, 0, 0]} scale={1.838} />
        <mesh geometry={nodes.Plane022_glass_0.geometry} material={materials.glass} position={[-934.777, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane023_glass_0.geometry} material={materials.glass} position={[-934.777, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane021_glass_0.geometry} material={materials.glass} position={[-934.777, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane024_glass_0.geometry} material={materials.glass} position={[277.384, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane025_glass_0.geometry} material={materials.glass} position={[277.384, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane026_glass_0.geometry} material={materials.glass} position={[596.47, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane027_glass_0.geometry} material={materials.glass} position={[596.47, 570.832, -1047.945]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane030_wood1_0.geometry} material={materials.wood1} position={[-599.177, 563.595, -1030.129]} scale={[1.137, 1, 0.215]} />
        <mesh geometry={nodes.Plane032_wood1_0.geometry} material={materials.wood1} position={[632.422, 563.595, -1020.837]} scale={[1, 1, 0.215]} />
        <mesh geometry={nodes.Plane033_wood2_0.geometry} material={materials.wood2} position={[632.422, 563.595, -1020.837]} scale={[1, 1, 0.215]} />
        <mesh geometry={nodes.Plane034_wood1_0.geometry} material={materials.wood1} position={[632.422, 563.595, -1020.837]} scale={[1, 1, 0.215]} />
        <mesh geometry={nodes.Plane035_wood1_0.geometry} material={materials.wood1} position={[632.422, 563.595, -1020.837]} scale={[1, 1, 0.215]} />
        <mesh geometry={nodes.Plane036_wood2_0.geometry} material={materials.wood2} position={[632.422, 563.595, -1020.837]} scale={[1, 1, 0.215]} />
        <mesh geometry={nodes.Plane037_wood2_0.geometry} material={materials.wood2} position={[-599.177, 563.595, -1030.129]} scale={[1.137, 1, 0.215]} />
        <mesh geometry={nodes.Circle003_setka_0.geometry} material={materials.setka} position={[258.434, 245.822, -386.998]} rotation={[0, -1.298, 0]} scale={[0.39, 0.5, 0.397]} />
        <mesh geometry={nodes.Circle005_setka_0.geometry} material={materials.setka} position={[328.971, 245.822, -410.181]} rotation={[-0.071, -0.427, -0.047]} scale={[0.39, 0.5, 0.397]} />
        <mesh geometry={nodes.Plane049_paperwhite_0.geometry} material={materials['paper.white']} position={[316.442, 19.792, 698.354]} rotation={[1.125, 0.318, 0.508]} scale={[1.007, 1.059, 1.008]} />
        <mesh geometry={nodes.Plane017_Material002_0.geometry} material={materials['Material.002']} position={[-663.46, 18.331, -994.556]} scale={[4.665, 1, 0.346]} />
        <mesh geometry={nodes.Plane055_Material002_0.geometry} material={materials['Material.002']} position={[655.197, 18.331, -994.556]} scale={[4.665, 1, 0.346]} />
        <mesh geometry={nodes.Plane056_paperwhite_0.geometry} material={materials['paper.white']} position={[245.089, 11.372, 743.183]} rotation={[-0.101, -0.962, -0.071]} />
        <mesh geometry={nodes.Plane057_paperwhite_0.geometry} material={materials['paper.white']} position={[463.538, 7.995, 548.971]} rotation={[-0.101, -0.962, -0.071]} scale={0.734} />
        <mesh geometry={nodes.Plane058_paperwhite_0.geometry} material={materials['paper.white']} position={[339.526, 7.995, 632.618]} rotation={[-0.101, -0.962, -0.071]} scale={0.734} />
        <mesh geometry={nodes.Plane059_paperwhite_0.geometry} material={materials['paper.white']} position={[-363.009, 11.372, 822.374]} rotation={[-0.076, 0.715, 0.062]} />
        <mesh geometry={nodes.Plane060_paperwhite_0.geometry} material={materials['paper.white']} position={[-494.278, 7.995, 626.447]} rotation={[-0.076, 0.715, 0.062]} scale={0.734} />
        <mesh geometry={nodes.Plane061_paperwhite_0.geometry} material={materials['paper.white']} position={[-288.824, 7.995, 577.475]} rotation={[-0.076, 0.715, 0.062]} scale={0.734} />
        <mesh geometry={nodes.Plane011_poster3_0.geometry} material={materials.poster3} position={[-82.67, 2.677, 1125.062]} scale={0.885} />
        <mesh geometry={nodes.Plane065_poster3_0.geometry} material={materials.poster3} position={[-723.75, 2.677, 699.008]} scale={1.356} />
        <mesh geometry={nodes.Plane066_Material_0.geometry} material={materials.Material} position={[-751.152, 12.941, 900.391]} scale={[1, 0.749, 1]} />
        <mesh geometry={nodes.Plane068_Material_0.geometry} material={materials.Material} position={[-847.736, 16.205, 1185.996]} scale={[1, 0.914, 1]} />
        <mesh geometry={nodes.Plane069_Material_0.geometry} material={materials.Material} position={[112.897, 12.941, 900.391]} scale={[1, 0.749, 1]} />
        <mesh geometry={nodes.Plane070_Material_0.geometry} material={materials.Material} position={[213.826, 16.26, 1010.462]} scale={[1.411, 1.057, 1.411]} />
        <mesh geometry={nodes.Plane071_Material_0.geometry} material={materials.Material} position={[101.932, 13.848, 1208.241]} scale={[2.146, 1.057, 1.411]} />
        <mesh geometry={nodes.Plane067_Material_0.geometry} material={materials.Material} position={[-910.285, 16.205, -948.528]} scale={[1, 0.914, 1]} />
        <mesh geometry={nodes.Plane072_paperwhite_0.geometry} material={materials['paper.white']} position={[245.089, 6.675, 280.772]} scale={[0.417, 0.417, 0.251]} />
        <mesh geometry={nodes.Plane073_paperwhite_0.geometry} material={materials['paper.white']} position={[245.089, 6.675, 502.208]} rotation={[0, -1.144, 0]} scale={[0.365, 0.365, 0.219]} />
        <mesh geometry={nodes.Plane074_paperwhite_0.geometry} material={materials['paper.white']} position={[-108.641, 6.675, 555.23]} rotation={[0, -1.144, 0]} scale={[0.343, 0.365, 0.144]} />
        <mesh geometry={nodes.Plane076_paperwhite_0.geometry} material={materials['paper.white']} position={[-831.068, 4.109, 302.423]} rotation={[0.249, -1.156, 0.18]} scale={[0.436, 0.368, 0.349]} />
        <mesh geometry={nodes.Plane077_paperwhite_0.geometry} material={materials['paper.white']} position={[-764.221, 12.152, 663.686]} rotation={[0.249, -1.156, 0.18]} scale={[0.436, 0.368, 0.349]} />
        <mesh geometry={nodes.Plane078_Black_0.geometry} material={materials.Black} position={[5.3, 999.031, 115.389]} scale={11.774} />
        <mesh geometry={nodes.Plane079_Material001_0.geometry} material={materials['Material.001']} position={[13.174, 1009.922, 101.182]} scale={11.774} />
        <mesh geometry={nodes.Vert001_black2_0.geometry} material={materials['black.2']} position={[-707.719, 1009.673, 257.95]} />
        <mesh geometry={nodes.Vert004_black2_0.geometry} material={materials['black.2']} position={[-282.154, 814.524, 638.339]} />
        <mesh geometry={nodes.Vert003_black2_0.geometry} material={materials['black.2']} position={[-361.116, 814.524, 638.339]} />
        <mesh geometry={nodes.Vert005_black2_0.geometry} material={materials['black.2']} position={[-455.225, 814.524, 638.339]} />
        <mesh geometry={nodes.Plane089_lamp2_0.geometry} material={materials.lamp2} position={[-457.244, 21.776, 428.606]} />
        <mesh geometry={nodes.Plane075_paperwhite_0.geometry} material={materials['paper.white']} position={[395.904, 11.372, 851.938]} rotation={[-0.101, -0.962, -0.071]} />
      </group>
      </group>
      </RigidBody>
    </>
  )
}

useGLTF.preload('/day_3._abandoned_school_room.glb')
