/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/warehouse_free_low-poly_for_games.glb -o src/components/WarehouseRoom.tsx -t 
Author: dasy444 (https://sketchfab.com/dasy444)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/warehouse-free-low-poly-for-games-32eeb06ebf8a45db85ea5f98b26f33de
Title: warehouse FREE LOW-POLY FOR GAMES
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material010_0: THREE.Mesh
    ['Cube001_������_0']: THREE.Mesh
    ['Cube002_������_0']: THREE.Mesh
    ['Cube003_������_0']: THREE.Mesh
    ['Cube004_������_0']: THREE.Mesh
    Cube005_Material008_0: THREE.Mesh
    Cube006_Material006_0: THREE.Mesh
    Cube007_Material006_0: THREE.Mesh
    Cube008_Material007_0: THREE.Mesh
    Cube009_Material006_0: THREE.Mesh
    Cube010_Material008_0: THREE.Mesh
    Cube011_Material010_0: THREE.Mesh
    Cube012_Material010_0: THREE.Mesh
    Cube013_Material010_0: THREE.Mesh
    Cube014_Material014_0: THREE.Mesh
    Cube014_Material015_0: THREE.Mesh
    Cube015_Material007_0: THREE.Mesh
    Cube016_Material007_0: THREE.Mesh
    Cube016_Material016_0: THREE.Mesh
    Cube017_Material017_0: THREE.Mesh
    Cube018_Material018_0: THREE.Mesh
    Cube019_Material019_0: THREE.Mesh
    Cube020_Material019_0: THREE.Mesh
    Cube021_Material020_0: THREE.Mesh
    Cube022_Material020_0: THREE.Mesh
    Cube023_Material021_0: THREE.Mesh
    Cube024_Material022_0: THREE.Mesh
    Cube025_Material022_0: THREE.Mesh
    Cube026_Material023_0: THREE.Mesh
    Cube026_Material024_0: THREE.Mesh
    Cube026_Material009_0: THREE.Mesh
    Cube027_Material021_0: THREE.Mesh
    Cube028_Material021_0: THREE.Mesh
    Cube029_Material025_0: THREE.Mesh
    Cube029_Material024_0: THREE.Mesh
    Cube029_Material009_0: THREE.Mesh
    Cube030_Material026_0: THREE.Mesh
    Cube030_Material024_0: THREE.Mesh
    Cube030_Material009_0: THREE.Mesh
    Cube031_Material027_0: THREE.Mesh
    Cube032_Material027_0: THREE.Mesh
    Cube033_Material028_0: THREE.Mesh
    Cube034_Material027_0: THREE.Mesh
    Cube035_Material018_0: THREE.Mesh
    Cube036_Material018_0: THREE.Mesh
    Cube037_Material017_0: THREE.Mesh
    Cube038_Material017_0: THREE.Mesh
    Cube039_Material026_0: THREE.Mesh
    Cube039_Material024_0: THREE.Mesh
    Cube039_Material009_0: THREE.Mesh
    Cube040_Material022_0: THREE.Mesh
    Cube041_Material029_0: THREE.Mesh
    Cube042_Material018_0: THREE.Mesh
    Cube043_Material023_0: THREE.Mesh
    Cube043_Material024_0: THREE.Mesh
    Cube043_Material009_0: THREE.Mesh
    Cube044_Material031_0: THREE.Mesh
    Cube045_Material030_0: THREE.Mesh
    Cube046_Material031_0: THREE.Mesh
    Cube047_Material031_0: THREE.Mesh
    Cube048_Material030_0: THREE.Mesh
    Cube049_Material009_0: THREE.Mesh
    Cube050_Material018_0: THREE.Mesh
    Cube051_Material018_0: THREE.Mesh
    Cube052_Material031_0: THREE.Mesh
    Cube053_Material018_0: THREE.Mesh
    Cube054_Material021_0: THREE.Mesh
    Cube055_Material035_0: THREE.Mesh
    Cube056_Material035_0: THREE.Mesh
    Cube057_Material035_0: THREE.Mesh
    Cube058_Material028_0: THREE.Mesh
    Cube059_Material034_0: THREE.Mesh
    Cube060_Material034_0: THREE.Mesh
    Cube061_Material018_0: THREE.Mesh
    Cube062_Material020_0: THREE.Mesh
    Cube063_Material019_0: THREE.Mesh
    Cube064_Material022_0: THREE.Mesh
    Cube065_Material023_0: THREE.Mesh
    Cube065_Material024_0: THREE.Mesh
    Cube065_Material009_0: THREE.Mesh
    Cube066_Material022_0: THREE.Mesh
    Cube067_Material021_0: THREE.Mesh
    Cube068_Material025_0: THREE.Mesh
    Cube068_Material024_0: THREE.Mesh
    Cube068_Material009_0: THREE.Mesh
    Cube069_Material026_0: THREE.Mesh
    Cube069_Material024_0: THREE.Mesh
    Cube069_Material009_0: THREE.Mesh
    Cube070_Material027_0: THREE.Mesh
    Cube071_Material028_0: THREE.Mesh
    Cube072_Material017_0: THREE.Mesh
    Cube073_Material030_0: THREE.Mesh
    Cube074_Material031_0: THREE.Mesh
    Cube075_Material035_0: THREE.Mesh
    ['Cylinder_������_0']: THREE.Mesh
    Cylinder_Material037_0: THREE.Mesh
    ['Cylinder001_������_0']: THREE.Mesh
    Cylinder001_Material037_0: THREE.Mesh
    Plane_Material001_0: THREE.Mesh
    Plane001_Material009_0: THREE.Mesh
    Plane002_Material003_0: THREE.Mesh
    Plane002_Material002_0: THREE.Mesh
    Plane003_Material004_0: THREE.Mesh
    Plane004_Material005_0: THREE.Mesh
    Plane005_Material011_0: THREE.Mesh
    Plane006_Material012_0: THREE.Mesh
    Plane007_Material013_0: THREE.Mesh
    Plane008_Material032_0: THREE.Mesh
    Plane008_Material034_0: THREE.Mesh
    Plane009_Material036_0: THREE.Mesh
    Plane010_Material036_0: THREE.Mesh
    Plane011_Material003_0: THREE.Mesh
    Plane011_Material002_0: THREE.Mesh
    Plane012_Material032_0: THREE.Mesh
    Plane012_Material034_0: THREE.Mesh
    Sphere_Material039_0: THREE.Mesh
  }
  materials: {
    ['Material.010']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/warehouse_free_low-poly_for_games.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-81.857, 462.236, -825.334]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube014_Material014_0.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.Cube014_Material015_0.geometry} material={materials['Material.015']} />
        </group>
        <group position={[-454.759, -6.002, 300.941]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Cube016_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube016_Material016_0.geometry} material={materials['Material.016']} />
        </group>
        <group position={[122.032, 0.729, 165.195]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Cube026_Material023_0.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Cube026_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube026_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-42.064, 58.092, 37.386]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube029_Material025_0.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Cube029_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube029_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-42.064, 58.092, -37.991]} rotation={[-Math.PI / 2, 0, -0.652]} scale={100}>
          <mesh geometry={nodes.Cube030_Material026_0.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Cube030_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube030_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[98.946, 58.092, 60.377]} rotation={[-Math.PI / 2, 0, -3.095]} scale={100}>
          <mesh geometry={nodes.Cube039_Material026_0.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Cube039_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube039_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-43.644, 13.352, -112.287]} rotation={[-Math.PI / 2, 0, 0.697]} scale={100}>
          <mesh geometry={nodes.Cube043_Material023_0.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Cube043_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube043_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-169.14, 3383.976, 137.129]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Cube065_Material023_0.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Cube065_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube065_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-84.865, 3441.338, 128.682]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube068_Material025_0.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Cube068_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube068_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-16.142, 3441.338, 122.029]} rotation={[-Math.PI / 2, 0, -0.652]} scale={100}>
          <mesh geometry={nodes.Cube069_Material026_0.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Cube069_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube069_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-132.619, 366.184, 19.764]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['Cylinder_������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder_Material037_0.geometry} material={materials['Material.037']} />
        </group>
        <group position={[191.092, 366.184, 19.764]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['Cylinder001_������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder001_Material037_0.geometry} material={materials['Material.037']} />
        </group>
        <group position={[-606.207, 418.444, -764.069]} rotation={[0, Math.PI / 2, 0]} scale={100}>
          <mesh geometry={nodes.Plane002_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane002_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-81.599, 344.629, -985.024]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane008_Material032_0.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.Plane008_Material034_0.geometry} material={materials['Material.034']} />
        </group>
        <group position={[641.496, 418.444, 875.143]} rotation={[0, -Math.PI / 2, 0]} scale={100}>
          <mesh geometry={nodes.Plane011_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane011_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-3.214, 3460.865, -172.426]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane012_Material032_0.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.Plane012_Material034_0.geometry} material={materials['Material.034']} />
        </group>
        <mesh geometry={nodes.Cube_Material010_0.geometry} material={materials['Material.010']} position={[135.44, 268.67, -600.752]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['Cube001_������_0'].geometry} material={materials.material} position={[49.906, 857.037, -1025.828]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['Cube002_������_0'].geometry} material={materials.material} position={[-566.267, 582.867, 31.463]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['Cube003_������_0'].geometry} material={materials.material} position={[-440.898, 629.007, 31.463]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['Cube004_������_0'].geometry} material={materials.material} position={[-144.657, 743.426, 31.463]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube005_Material008_0.geometry} material={materials['Material.008']} position={[-458.861, 188.844, -832.743]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube006_Material006_0.geometry} material={materials['Material.006']} position={[477.52, -4.291, -371.058]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube007_Material006_0.geometry} material={materials['Material.006']} position={[477.52, 220.212, -371.058]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube008_Material007_0.geometry} material={materials['Material.007']} position={[-454.759, -6.002, -400.304]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube009_Material006_0.geometry} material={materials['Material.006']} position={[-455.547, 191.543, -400.304]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} position={[-458.861, -4.042, -832.743]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube011_Material010_0.geometry} material={materials['Material.010']} position={[126.012, 236.325, -623.294]} rotation={[Math.PI, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube012_Material010_0.geometry} material={materials['Material.010']} position={[-293.101, 236.325, -623.294]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
        <mesh geometry={nodes.Cube013_Material010_0.geometry} material={materials['Material.010']} position={[126.012, 236.325, -1025.591]} rotation={[Math.PI, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube015_Material007_0.geometry} material={materials['Material.007']} position={[-454.759, -6.002, 561.791]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube017_Material017_0.geometry} material={materials['Material.017']} position={[-474.761, -2.186, 157.778]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube018_Material018_0.geometry} material={materials['Material.018']} position={[-286.27, 6.172, -354.115]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube019_Material019_0.geometry} material={materials['Material.019']} position={[-81.657, -1.037, 77.786]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube020_Material019_0.geometry} material={materials['Material.019']} position={[98.475, -1.037, 77.786]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube021_Material020_0.geometry} material={materials['Material.020']} position={[-358.671, 1.204, 261.794]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube022_Material020_0.geometry} material={materials['Material.020']} position={[-467.106, 1.204, 265.392]} rotation={[-Math.PI / 2, 0, 0.297]} scale={100} />
        <mesh geometry={nodes.Cube023_Material021_0.geometry} material={materials['Material.021']} position={[-331.832, 1.734, 342.512]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube024_Material022_0.geometry} material={materials['Material.022']} position={[-409.928, 0.449, 340.833]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube025_Material022_0.geometry} material={materials['Material.022']} position={[97.944, 59.53, 107.636]} rotation={[-Math.PI / 2, 0, -2.074]} scale={100} />
        <mesh geometry={nodes.Cube027_Material021_0.geometry} material={materials['Material.021']} position={[-47.121, 13.8, 111.693]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube028_Material021_0.geometry} material={materials['Material.021']} position={[-47.121, 13.8, 71.42]} rotation={[-Math.PI / 2, 0, -1.441]} scale={100} />
        <mesh geometry={nodes.Cube031_Material027_0.geometry} material={materials['Material.027']} position={[-47.121, 58.604, 89.056]} rotation={[-Math.PI / 2, 0, -1.588]} scale={100} />
        <mesh geometry={nodes.Cube032_Material027_0.geometry} material={materials['Material.027']} position={[-47.121, 58.604, 109.449]} rotation={[-Math.PI / 2, 0, -1.588]} scale={100} />
        <mesh geometry={nodes.Cube033_Material028_0.geometry} material={materials['Material.028']} position={[132.113, 58.604, -70.397]} rotation={[-Math.PI / 2, 0, -1.588]} scale={100} />
        <mesh geometry={nodes.Cube034_Material027_0.geometry} material={materials['Material.027']} position={[125.545, 58.604, -87.702]} rotation={[-Math.PI / 2, 0, -1.588]} scale={100} />
        <mesh geometry={nodes.Cube035_Material018_0.geometry} material={materials['Material.018']} position={[-78.591, 13.224, -2.546]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube036_Material018_0.geometry} material={materials['Material.018']} position={[-51.445, 13.224, -46.439]} rotation={[-Math.PI / 2, 0, -0.174]} scale={100} />
        <mesh geometry={nodes.Cube037_Material017_0.geometry} material={materials['Material.017']} position={[-474.761, -2.186, 60.608]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube038_Material017_0.geometry} material={materials['Material.017']} position={[-474.761, -2.186, -37.75]} rotation={[-Math.PI / 2, 0, -1.281]} scale={100} />
        <mesh geometry={nodes.Cube040_Material022_0.geometry} material={materials['Material.022']} position={[97.944, 59.53, -168.8]} rotation={[-Math.PI / 2, 0, -1.452]} scale={100} />
        <mesh geometry={nodes.Cube041_Material029_0.geometry} material={materials['Material.029']} position={[93.694, 57.193, 16.112]} rotation={[-Math.PI / 2, 0, 0.16]} scale={100} />
        <mesh geometry={nodes.Cube042_Material018_0.geometry} material={materials['Material.018']} position={[134.616, 13.224, 39.366]} rotation={[-Math.PI / 2, 0, -0.033]} scale={100} />
        <mesh geometry={nodes.Cube044_Material031_0.geometry} material={materials['Material.031']} position={[-191.957, 106.713, -983.864]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube045_Material030_0.geometry} material={materials['Material.030']} position={[-6.062, 2.39, -992.357]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
        <mesh geometry={nodes.Cube046_Material031_0.geometry} material={materials['Material.031']} position={[376.622, 106.713, -983.864]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube047_Material031_0.geometry} material={materials['Material.031']} position={[502.405, 106.713, -983.864]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube048_Material030_0.geometry} material={materials['Material.030']} position={[295.212, 269.478, -909.246]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube049_Material009_0.geometry} material={materials['Material.009']} position={[264.108, 0.78, -588.746]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube050_Material018_0.geometry} material={materials['Material.018']} position={[-248.378, 269.077, -651.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube051_Material018_0.geometry} material={materials['Material.018']} position={[-151.091, 269.077, -651.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube052_Material031_0.geometry} material={materials['Material.031']} position={[502.405, 106.713, -758.588]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube053_Material018_0.geometry} material={materials['Material.018']} position={[-286.27, 6.172, -479.983]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube054_Material021_0.geometry} material={materials['Material.021']} position={[-281.61, 1.734, -957.65]} rotation={[-Math.PI / 2, 0, 0.099]} scale={100} />
        <mesh geometry={nodes.Cube055_Material035_0.geometry} material={materials['Material.035']} position={[-75.453, 136.876, -996.917]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube056_Material035_0.geometry} material={materials['Material.035']} position={[-27.127, 136.876, -996.917]} rotation={[-Math.PI / 2, 0, 2.453]} scale={100} />
        <mesh geometry={nodes.Cube057_Material035_0.geometry} material={materials['Material.035']} position={[20.459, 136.876, -996.917]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube058_Material028_0.geometry} material={materials['Material.028']} position={[-98.999, 80.739, -996.185]} rotation={[-Math.PI / 2, 0, -3.014]} scale={100} />
        <mesh geometry={nodes.Cube059_Material034_0.geometry} material={materials['Material.034']} position={[-191.957, 264.96, -818.108]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube060_Material034_0.geometry} material={materials['Material.034']} position={[82.698, 264.96, -818.108]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube061_Material018_0.geometry} material={materials['Material.018']} position={[-301.27, 3389.418, -25.009]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube062_Material020_0.geometry} material={materials['Material.020']} position={[-294.696, 3384.45, 195.914]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube063_Material019_0.geometry} material={materials['Material.019']} position={[227.942, 3381.325, 77.787]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube064_Material022_0.geometry} material={materials['Material.022']} position={[-286.924, 3383.696, 278.425]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube066_Material022_0.geometry} material={materials['Material.022']} position={[156.419, 3442.776, 158.541]} rotation={[-Math.PI / 2, 0, -2.074]} scale={100} />
        <mesh geometry={nodes.Cube067_Material021_0.geometry} material={materials['Material.021']} position={[81.284, 3397.047, 145.837]} rotation={[-Math.PI / 2, 0, -1.441]} scale={100} />
        <mesh geometry={nodes.Cube070_Material027_0.geometry} material={materials['Material.027']} position={[137.348, 3441.85, 120.567]} rotation={[-Math.PI / 2, 0, -1.588]} scale={100} />
        <mesh geometry={nodes.Cube071_Material028_0.geometry} material={materials['Material.028']} position={[48.776, 3441.85, 120.391]} rotation={[-Math.PI / 2, 0, -1.588]} scale={100} />
        <mesh geometry={nodes.Cube072_Material017_0.geometry} material={materials['Material.017']} position={[-310.957, 3381.06, 93.425]} rotation={[-Math.PI / 2, 0, -1.281]} scale={100} />
        <mesh geometry={nodes.Cube073_Material030_0.geometry} material={materials['Material.030']} position={[72.323, 3385.636, -95.756]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
        <mesh geometry={nodes.Cube074_Material031_0.geometry} material={materials['Material.031']} position={[-132.323, 3489.959, -94.555]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube075_Material035_0.geometry} material={materials['Material.035']} position={[-75.453, 3423.703, 72.196]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane001_Material009_0.geometry} material={materials['Material.009']} position={[135.44, 268.67, -807.446]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane003_Material004_0.geometry} material={materials['Material.004']} position={[0, 427.267, -1044.254]} scale={100} />
        <mesh geometry={nodes.Plane004_Material005_0.geometry} material={materials['Material.005']} position={[0, 588.333, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane005_Material011_0.geometry} material={materials['Material.011']} position={[135.44, 314.191, -611.762]} scale={100} />
        <mesh geometry={nodes.Plane006_Material012_0.geometry} material={materials['Material.012']} position={[135.44, 401.805, -611.762]} scale={100.266} />
        <mesh geometry={nodes.Plane007_Material013_0.geometry} material={materials['Material.013']} position={[135.44, 401.805, -611.762]} scale={100} />
        <mesh geometry={nodes.Plane009_Material036_0.geometry} material={materials['Material.036']} position={[-75.453, 459.168, -754.283]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane010_Material036_0.geometry} material={materials['Material.036']} position={[-75.453, 459.168, -916.397]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Sphere_Material039_0.geometry} material={materials['Material.039']} position={[68.149, 169.367, -35.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/warehouse_free_low-poly_for_games.glb')
